// remote/panel/src/components/Library.svelte
<script>
  // The document library — one central directory of markdown files living in
  // ~/.mission-control/library on the Mac, written by you OR by agents (a
  // research agent streams its report straight into a file here). This view is
  // the reading room: filter by kind/status/tag, search titles instantly and
  // bodies over the wire, and open any doc into its full-screen workspace.
  //
  // Kinds carry a colour the whole app speaks: plan = accent cyan, research =
  // mgr violet, note = neutral ink. The maps below hold FULL Tailwind class
  // strings (never interpolated) so the JIT actually emits them.
  import {
    mc,
    docCreate,
    docSearch,
    research,
    launch,
    toast,
    kindLabel,
    docStatusLabel,
    allTags,
    filterDocs,
  } from '../lib/store.svelte.js';
  import { dictate, speechSupported } from '../lib/speech.js';
  import { ago } from '../lib/md.js';
  import Icon from './Icon.svelte';

  let { onopen } = $props(); // onopen(docId)

  const KIND = {
    plan: { icon: 'plan', text: 'text-accent', ring: 'border-accent/40 bg-accent/10 text-accent', chip: 'border-accent/30 text-accent', spine: 'from-accent/60 via-accent/20' },
    research: { icon: 'research', text: 'text-mgr', ring: 'border-mgr/40 bg-mgr/10 text-mgr', chip: 'border-mgr/30 text-mgr', spine: 'from-mgr/60 via-mgr/20' },
    note: { icon: 'note', text: 'text-ink2', ring: 'border-line2 bg-raised/60 text-ink2', chip: 'border-line2 text-ink3', spine: 'from-line2 via-line' },
  };
  const kindOf = (k) => KIND[k] || KIND.note;

  const STATUS = {
    draft: 'border-line2 text-ink3',
    active: 'border-accent/40 text-accent',
    done: 'border-ok/40 text-ok',
    archived: 'border-line text-ink3/70',
  };
  const statusChip = (s) => STATUS[s] || STATUS.draft;

  // Older Mac hosts predate the whole library — they ship no `docs` field at all.
  const hostTooOld = $derived(!!mc.snapshot && !('docs' in mc.snapshot));

  // ---- filters + search -------------------------------------------------------
  let kindFilter = $state('all');
  let statusFilter = $state('all');
  let tagFilter = $state('all');
  let q = $state('');

  const tags = $derived(allTags(mc.docs));

  // Instant local sieve over the metadata every card already shows.
  const localDocs = $derived(filterDocs(mc.docs, { kind: kindFilter, status: statusFilter, tag: tagFilter, q }));

  // Kind chip counts respect the OTHER active filters (status/tag/query) so a
  // count reads as "how many I'd see if I picked this kind", not a raw total.
  function kindCount(k) {
    return filterDocs(mc.docs, { kind: k, status: statusFilter, tag: tagFilter, q }).length;
  }

  const KIND_TABS = [
    ['all', 'All'],
    ['plan', 'Plans'],
    ['research', 'Research'],
    ['note', 'Notes'],
  ];
  const STATUS_TABS = [
    ['all', 'All'],
    ['draft', 'Draft'],
    ['active', 'Working'],
    ['done', 'Done'],
    ['archived', 'Archived'],
  ];

  // Full-text body search over the wire, debounced. The host answers into
  // mc.search; we only trust a result whose `q` still matches what's typed, so a
  // slow reply for an old query can never clobber the current one.
  let searchTimer;
  $effect(() => {
    const query = q.trim();
    clearTimeout(searchTimer);
    if (query.length < 2 || mc.link !== 'linked') return;
    searchTimer = setTimeout(() => docSearch(query), 350);
    return () => clearTimeout(searchTimer);
  });

  // Docs the local sieve missed but the host found deep in a body. Only shown for
  // the CURRENT query, and never duplicating a card already on screen.
  const bodyHits = $derived.by(() => {
    const query = q.trim();
    if (query.length < 2 || !mc.search || mc.search.q !== query) return [];
    const shown = new Set(localDocs.map((d) => d.id));
    const out = [];
    for (const hit of mc.search.hits || []) {
      if (shown.has(hit.id)) continue;
      const meta = mc.docs.find((d) => d.id === hit.id);
      if (meta) out.push({ meta, snippets: hit.snippets || [] });
    }
    return out;
  });

  // Escape agent-authored snippet text BEFORE wrapping query matches in <mark>:
  // the snippet is arbitrary repo/body content and must never reach {@html} raw.
  function esc(s) {
    return String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
  }
  function highlight(snippet) {
    const safe = esc(snippet);
    const query = q.trim();
    if (!query) return safe;
    const rx = new RegExp('(' + query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + ')', 'ig');
    return safe.replace(rx, '<mark>$1</mark>');
  }

  const FALLBACK_MODELS = [
    { flag: 'claude-fable-5', label: 'Fable 5' },
    { flag: 'opus', label: 'Opus 4.8' },
    { flag: 'claude-sonnet-5', label: 'Sonnet 5' },
  ];
  const models = $derived(mc.models.length ? mc.models : FALLBACK_MODELS);

  // ---- new-doc kind picker ----------------------------------------------------
  let picking = $state(false);
  function newDoc(kind) {
    picking = false;
    if (kind === 'research') {
      researching = true;
      return;
    }
    // Created on the Mac; the docCreate ack carries the id and App opens it in
    // the editor (a hand-made doc is empty — you type into it now).
    docCreate({ title: `Untitled ${kindLabel(kind).toLowerCase()}`, kind, dir: mc.lastDir || '' });
  }

  // ---- research sheet ---------------------------------------------------------
  // One agent researches a topic and writes its report straight into a new
  // library file; you read it here as it lands.
  let researching = $state(false);
  let rTopic = $state('');
  let rSubject = $state('');
  let rTags = $state('');
  let rDir = $state('');
  let rModel = $state('opus');
  let rDirTouched = false;
  $effect(() => {
    if (researching && !rDirTouched && !rDir && mc.lastDir) rDir = mc.lastDir;
  });

  let rMic = $state(null);
  function toggleResearchMic() {
    if (rMic) {
      rMic.stop();
      return;
    }
    rMic = dictate({ base: rTopic, onText: (t) => (rTopic = t), onEnd: () => (rMic = null), onError: () => (rMic = null) });
  }

  function toTags(s) {
    return (s || '')
      .split(',')
      .map((t) => t.trim())
      .filter(Boolean);
  }

  function launchResearch() {
    const topic = rTopic.trim();
    if (!topic) return toast('What should the agent research?');
    const fix = (f) => (f === 'default' ? '' : f);
    if (!research({ topic, subject: rSubject.trim(), dir: rDir.trim(), model: fix(rModel), tags: toTags(rTags) })) return;
    researching = false;
    rTopic = '';
    rSubject = '';
    rTags = '';
    toast('Research agent launched — its report lands here');
  }

  // ---- draft-a-plan-with-agent sheet ------------------------------------------
  // A read-only planning agent explores the project and presents a plan with
  // ExitPlanMode; the Mac captures that plan into the library automatically.
  let drafting = $state(false);
  let goal = $state('');
  let dDir = $state('');
  let dModel = $state('opus');
  let dDirTouched = false;
  $effect(() => {
    if (drafting && !dDirTouched && !dDir && mc.lastDir) dDir = mc.lastDir;
  });

  let dMic = $state(null);
  function toggleDraftMic() {
    if (dMic) {
      dMic.stop();
      return;
    }
    dMic = dictate({ base: goal, onText: (t) => (goal = t), onEnd: () => (dMic = null), onError: () => (dMic = null) });
  }

  function draftMission(g) {
    return (
      'Research this project and draft a thorough implementation plan for the goal below. Do NOT write any code — you are in plan mode. ' +
      'Explore the codebase first, then produce one complete, well-structured markdown plan: a clear title as a # heading, context, a concrete step-by-step approach naming the exact files to touch, risks, and how to verify. ' +
      'Present the finished plan with ExitPlanMode — Mission Control saves it to the library automatically.\n\nGOAL: ' +
      g
    );
  }
  function launchDraft() {
    const g = goal.trim();
    if (!g) return toast('Describe what to plan first');
    const fix = (f) => (f === 'default' ? '' : f);
    if (!launch({ mission: draftMission(g), dir: dDir.trim(), managerModel: null, workerModels: [fix(dModel)], planMode: true })) return;
    drafting = false;
    goal = '';
    toast('Planning agent launched — its plan lands here when ready');
  }
</script>

<div class="mx-auto w-full max-w-[1400px] px-4 pt-5 sm:px-6">
  <div class="mb-4 flex flex-wrap items-center gap-2">
    <h1 class="display mr-auto text-[20px] font-semibold leading-none tracking-tight">Library</h1>
    <button onclick={() => (researching = true)} class="flex min-h-[40px] items-center gap-2 rounded-xl bg-ink px-3.5 py-2 text-[13px] font-semibold text-bg transition active:scale-95">
      <Icon name="research" size={15} /> Research
    </button>
    <button onclick={() => (drafting = true)} class="flex min-h-[40px] items-center gap-2 rounded-xl border border-line bg-surface px-3.5 py-2 text-[13px] font-medium text-ink2 transition hover:border-line2 active:scale-95">
      <Icon name="bolt" size={15} /> Draft plan
    </button>
    <button onclick={() => (picking = true)} class="flex min-h-[40px] items-center gap-2 rounded-xl border border-line bg-surface px-3.5 py-2 text-[13px] font-medium text-ink2 transition hover:border-line2 active:scale-95">
      <Icon name="note" size={15} /> New doc
    </button>
  </div>

  {#if hostTooOld}
    <div class="panel rounded-2xl p-8 text-center">
      <div class="text-[16px] font-semibold">Your Mac app is out of date</div>
      <p class="mx-auto mt-2 max-w-[440px] text-[13px] leading-relaxed text-ink3">The document library lives on your Mac. Rebuild and relaunch Mission Control there to start syncing plans, research, and notes.</p>
    </div>
  {:else}
    <!-- one control row: search · kind · status -->
    <div class="mb-3 flex flex-wrap items-center gap-2">
      <div class="relative min-w-[200px] flex-1 sm:max-w-sm">
        <span class="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-ink3"><Icon name="search" size={16} /></span>
        <input
          bind:value={q}
          placeholder="Search titles and full text…"
          class="panel h-10 w-full rounded-xl pl-10 pr-9 text-[14px] outline-none transition focus:border-line2" />
        {#if q.trim()}
          <button onclick={() => (q = '')} aria-label="Clear search" class="absolute right-2 top-1/2 grid h-7 w-7 -translate-y-1/2 place-items-center rounded-lg text-ink3 transition hover:bg-raised hover:text-ink2">✕</button>
        {/if}
      </div>
      <div class="flex overflow-hidden rounded-xl border border-line">
        {#each KIND_TABS as [k, label]}
          <button onclick={() => (kindFilter = k)} class="flex min-h-[38px] items-center gap-1.5 px-3.5 text-[13px] font-medium transition {kindFilter === k ? 'bg-raised text-ink' : 'text-ink3 hover:text-ink2'}">
            {label}
            <span class="text-[11.5px] tabular-nums {kindFilter === k ? 'text-ink3' : 'text-ink3/70'}">{kindCount(k)}</span>
          </button>
        {/each}
      </div>
      <select bind:value={statusFilter} aria-label="Status filter" class="min-h-[38px] rounded-xl border border-line bg-surface px-3 text-[13px] text-ink2 outline-none transition focus:border-line2">
        {#each STATUS_TABS as [s, label]}<option value={s}>{s === 'all' ? 'Any status' : label}</option>{/each}
      </select>
    </div>

    {#if tags.length}
      <div class="mb-4 flex flex-wrap gap-1.5">
        {#each tags as t}
          <button onclick={() => (tagFilter = tagFilter === t ? 'all' : t)} class="min-h-[30px] rounded-full border px-3 py-1 text-[12px] transition active:scale-95 {tagFilter === t ? 'border-accent/40 bg-accent/10 text-accent' : 'border-line text-ink3 hover:border-line2'}">#{t}</button>
        {/each}
      </div>
    {:else}
      <div class="mb-1"></div>
    {/if}

    {#if !mc.docs.length}
      <div class="panel rounded-2xl p-8 text-center">
        <div class="mx-auto mb-3 grid h-14 w-14 place-items-center rounded-2xl border border-line bg-raised/60 text-ink3"><Icon name="book" size={26} /></div>
        <div class="text-[16px] font-semibold">Your library is empty</div>
        <p class="mx-auto mt-2 max-w-[480px] text-[13px] leading-relaxed text-ink3">
          The library is a folder of markdown files (<span class="font-mono text-[12px] text-ink2">~/.mission-control/library</span>) on your Mac — written by you or by agents, readable from anywhere. Send an agent to research a topic, draft a plan, or start a note by hand.
        </p>
      </div>
    {:else if !localDocs.length && !bodyHits.length}
      <div class="panel rounded-2xl p-8 text-center">
        <div class="text-[15px] font-semibold">Nothing matches</div>
        <p class="mx-auto mt-2 max-w-[420px] text-[13px] leading-relaxed text-ink3">Try a different kind, status, tag, or search term.</p>
      </div>
    {:else}
      {#if localDocs.length}
        <div class="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">
          {#each localDocs as d (d.id)}
            {@render card(d)}
          {/each}
        </div>
      {/if}

      {#if bodyHits.length}
        <div class="mt-6 mb-3 flex items-baseline gap-2">
          <h2 class="text-[13px] font-semibold text-ink2">Found in body</h2>
          <span class="text-[13px] tabular-nums text-ink3">{bodyHits.length}</span>
        </div>
        <div class="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">
          {#each bodyHits as h (h.meta.id)}
            <button onclick={() => onopen(h.meta.id)} class="panel panel-hover anim-rise relative flex flex-col gap-2 overflow-hidden rounded-2xl p-4 text-left transition active:scale-[0.99]">
              <div class="flex items-start gap-3">
                <div class="grid h-9 w-9 flex-none place-items-center rounded-lg border {kindOf(h.meta.kind).ring}"><Icon name={kindOf(h.meta.kind).icon} size={17} /></div>
                <div class="min-w-0 flex-1">
                  <div class="truncate text-[15px] font-semibold leading-tight">{h.meta.title}</div>
                  {#if h.meta.subject}<div class="truncate text-[12.5px] text-ink2">{h.meta.subject}</div>{/if}
                </div>
              </div>
              <div class="flex flex-col gap-1.5">
                {#each h.snippets.slice(0, 3) as snip}
                  <p class="snippet line-clamp-2 rounded-lg border border-line bg-inset/60 px-2.5 py-1.5 font-mono text-[11.5px] leading-relaxed text-ink3">{@html highlight(snip)}</p>
                {/each}
              </div>
            </button>
          {/each}
        </div>
      {/if}
    {/if}
  {/if}
</div>

{#snippet card(d)}
  {@const k = kindOf(d.kind)}
  <button onclick={() => onopen(d.id)} class="panel panel-hover anim-rise relative flex flex-col gap-2 overflow-hidden rounded-2xl p-4 text-left transition active:scale-[0.99]">
    <div class="flex items-start gap-3">
      <div class="relative grid h-9 w-9 flex-none place-items-center rounded-lg border {k.ring}">
        <Icon name={k.icon} size={17} />
        {#if d.kind === 'research' && d.status === 'active'}
          <span class="absolute -right-1 -top-1 flex h-2.5 w-2.5"><span class="absolute inline-flex h-full w-full rounded-full bg-accent/70" style="animation:mc-ping 1.6s ease-out infinite"></span><span class="relative inline-flex h-2.5 w-2.5 rounded-full bg-accent"></span></span>
        {/if}
      </div>
      <div class="min-w-0 flex-1">
        <div class="truncate text-[15px] font-semibold leading-tight">{d.title}</div>
        {#if d.subject}<div class="mt-0.5 truncate text-[12.5px] {k.text}">{d.subject}</div>{/if}
      </div>
      <span class="flex-none rounded-md border px-1.5 py-px text-[10px] font-medium uppercase tracking-wide {statusChip(d.status)}">{docStatusLabel(d.status)}</span>
    </div>

    {#if d.preview}
      <p class="line-clamp-2 text-[12.5px] leading-relaxed text-ink3">{d.preview}</p>
    {/if}

    {#if (d.tags || []).length}
      <div class="flex flex-wrap gap-1.5">
        {#each d.tags.slice(0, 4) as t}
          <span class="rounded-md border {k.chip} px-1.5 py-px text-[11px]">#{t}</span>
        {/each}
      </div>
    {/if}

    <div class="mt-0.5 flex flex-wrap items-center gap-x-3 gap-y-1 text-[11.5px] text-ink3">
      {#if d.folder}<span class="flex items-center gap-1"><Icon name="folder" size={12} />{d.folder}</span>{/if}
      <span>{ago(d.updatedAt, mc.now)}</span>
      {#if d.words}<span>{d.words.toLocaleString()} words</span>{/if}
      <span class="rounded-md border px-1.5 py-px {d.session ? 'border-mgr/30 text-mgr' : 'border-line2 text-ink3'}">{d.session ? 'agent' : 'you'}</span>
    </div>
  </button>
{/snippet}

<!-- new-doc kind picker -->
{#if picking}
  <div class="fixed inset-0 z-[80] flex items-end justify-center bg-black/60 backdrop-blur-sm sm:items-center" onclick={(e) => e.target === e.currentTarget && (picking = false)} role="presentation">
    <div class="panel anim-rise w-full max-w-[460px] rounded-t-2xl p-5 sm:rounded-2xl" style="padding-bottom:calc(20px + var(--sab))">
      <div class="mb-4 flex items-center gap-3">
        <h3 class="flex-1 text-[16px] font-semibold">New document</h3>
        <button onclick={() => (picking = false)} aria-label="Close" class="grid h-10 w-10 flex-none place-items-center rounded-xl text-ink2 transition hover:bg-raised"><Icon name="close" size={20} /></button>
      </div>
      <div class="grid gap-2">
        {#each [['plan', 'A build plan you can hand to a fleet'], ['research', 'Send an agent to research and write it for you'], ['note', 'A free-form note to keep']] as [k, blurb]}
          {@const kk = kindOf(k)}
          <button onclick={() => newDoc(k)} class="flex items-center gap-3 rounded-xl border border-line bg-raised/50 p-3.5 text-left transition hover:border-line2 active:scale-[0.98]">
            <div class="grid h-10 w-10 flex-none place-items-center rounded-lg border {kk.ring}"><Icon name={kk.icon} size={18} /></div>
            <div class="min-w-0">
              <div class="text-[14px] font-semibold">{kindLabel(k)}</div>
              <div class="text-[12.5px] leading-snug text-ink3">{blurb}</div>
            </div>
          </button>
        {/each}
      </div>
    </div>
  </div>
{/if}

<!-- research sheet -->
{#if researching}
  <div class="fixed inset-0 z-[80] flex items-end justify-center bg-black/60 backdrop-blur-sm sm:items-center" onclick={(e) => e.target === e.currentTarget && (researching = false)} role="presentation">
    <div class="panel anim-rise w-full max-w-[560px] rounded-t-2xl p-5 sm:rounded-2xl" style="padding-bottom:calc(20px + var(--sab))">
      <div class="mb-4 flex items-center gap-2">
        <h3 class="flex-1 text-[16px] font-semibold">Research with an agent</h3>
        {#if speechSupported}
          <button onclick={toggleResearchMic} aria-label="Dictate topic" class="grid h-10 w-10 flex-none place-items-center rounded-xl border transition active:scale-95 {rMic ? 'border-crit bg-crit/12 text-crit' : 'border-line bg-raised/60 text-ink2'}" style={rMic ? 'animation:mc-ring 1.4s ease-out infinite' : ''}><Icon name="mic" size={18} /></button>
        {/if}
        <button onclick={() => (researching = false)} aria-label="Close" class="grid h-10 w-10 flex-none place-items-center rounded-xl text-ink2 transition hover:bg-raised"><Icon name="close" size={20} /></button>
      </div>
      <textarea bind:value={rTopic} rows="3" placeholder="What should the agent research?" class="min-h-20 w-full resize-y rounded-xl border border-line bg-inset px-4 py-3 text-[16px] leading-relaxed text-ink outline-none transition placeholder:text-ink3 focus:border-line2 noscroll"></textarea>
      <input bind:value={rSubject} placeholder="Subject / company (optional)" class="mt-3 w-full rounded-xl border border-line bg-inset px-4 py-3 text-[15px] text-ink outline-none transition placeholder:text-ink3 focus:border-line2" />
      <input bind:value={rTags} placeholder="Tags, comma separated (optional)" class="mt-3 w-full rounded-xl border border-line bg-inset px-4 py-3 text-[14px] text-ink outline-none transition placeholder:text-ink3 focus:border-line2" />
      <input bind:value={rDir} oninput={() => (rDirTouched = true)} placeholder="~/path/to/project (optional)" class="mt-3 w-full rounded-xl border border-line bg-inset px-4 py-3 font-mono text-[13px] text-ink outline-none transition placeholder:text-ink3 focus:border-line2" />
      {#if mc.knownDirs.length}
        <div class="mt-2 flex flex-wrap gap-1.5">
          {#each mc.knownDirs as dd}
            <button onclick={() => { rDir = dd; rDirTouched = true; }} class="min-h-[36px] rounded-lg border px-3 py-1.5 text-[13px] transition active:scale-95 {dd === rDir ? 'border-line2 bg-raised text-ink' : 'border-line text-ink2'}">{dd.split('/').filter(Boolean).pop() || dd}</button>
          {/each}
        </div>
      {/if}
      <div class="mt-4 flex items-center gap-3">
        <select bind:value={rModel} class="min-h-[46px] flex-1 rounded-xl border border-line bg-raised px-4 py-3 text-[14px] text-ink outline-none transition focus:border-line2">
          {#each models as m}<option value={m.flag}>{m.label}</option>{/each}
        </select>
        <button onclick={launchResearch} class="min-h-[46px] rounded-xl bg-ink px-5 text-[14px] font-semibold text-bg transition active:scale-95">Research</button>
      </div>
      <p class="mt-3 text-[12.5px] leading-relaxed text-ink3">One agent researches and writes its report straight into the library — you can read it here as it lands.</p>
    </div>
  </div>
{/if}

<!-- draft-a-plan-with-agent sheet -->
{#if drafting}
  <div class="fixed inset-0 z-[80] flex items-end justify-center bg-black/60 backdrop-blur-sm sm:items-center" onclick={(e) => e.target === e.currentTarget && (drafting = false)} role="presentation">
    <div class="panel anim-rise w-full max-w-[560px] rounded-t-2xl p-5 sm:rounded-2xl" style="padding-bottom:calc(20px + var(--sab))">
      <div class="mb-4 flex items-center gap-2">
        <h3 class="flex-1 text-[16px] font-semibold">Draft a plan with an agent</h3>
        {#if speechSupported}
          <button onclick={toggleDraftMic} aria-label="Dictate goal" class="grid h-10 w-10 flex-none place-items-center rounded-xl border transition active:scale-95 {dMic ? 'border-crit bg-crit/12 text-crit' : 'border-line bg-raised/60 text-ink2'}" style={dMic ? 'animation:mc-ring 1.4s ease-out infinite' : ''}><Icon name="mic" size={18} /></button>
        {/if}
        <button onclick={() => (drafting = false)} aria-label="Close" class="grid h-10 w-10 flex-none place-items-center rounded-xl text-ink2 transition hover:bg-raised"><Icon name="close" size={20} /></button>
      </div>
      <textarea bind:value={goal} rows="3" placeholder="What should the plan achieve?" class="min-h-20 w-full resize-y rounded-xl border border-line bg-inset px-4 py-3 text-[16px] leading-relaxed text-ink outline-none transition placeholder:text-ink3 focus:border-line2 noscroll"></textarea>
      <input bind:value={dDir} oninput={() => (dDirTouched = true)} placeholder="~/path/to/project" class="mt-3 w-full rounded-xl border border-line bg-inset px-4 py-3 font-mono text-[13px] text-ink outline-none transition placeholder:text-ink3 focus:border-line2" />
      {#if mc.knownDirs.length}
        <div class="mt-2 flex flex-wrap gap-1.5">
          {#each mc.knownDirs as dd}
            <button onclick={() => { dDir = dd; dDirTouched = true; }} class="min-h-[36px] rounded-lg border px-3 py-1.5 text-[13px] transition active:scale-95 {dd === dDir ? 'border-line2 bg-raised text-ink' : 'border-line text-ink2'}">{dd.split('/').filter(Boolean).pop() || dd}</button>
          {/each}
        </div>
      {/if}
      <div class="mt-4 flex items-center gap-3">
        <select bind:value={dModel} class="min-h-[46px] flex-1 rounded-xl border border-line bg-raised px-4 py-3 text-[14px] text-ink outline-none transition focus:border-line2">
          {#each models as m}<option value={m.flag}>{m.label}</option>{/each}
        </select>
        <button onclick={launchDraft} class="min-h-[46px] rounded-xl bg-ink px-5 text-[14px] font-semibold text-bg transition active:scale-95">Draft</button>
      </div>
      <p class="mt-3 text-[12.5px] leading-relaxed text-ink3">Launches one agent in read-only plan mode. It explores the project, drafts the plan, and the plan file appears here — nothing gets built until you say so.</p>
    </div>
  </div>
{/if}

<style>
  /* Search snippets arrive as escaped text with <mark> wrapped around query
     matches; Svelte scopes styles, so :global reaches the injected element. */
  .snippet :global(mark) {
    background: color-mix(in oklab, var(--color-accent) 30%, transparent);
    color: var(--color-accent-bright);
    border-radius: 3px;
    padding: 0 2px;
  }
</style>

// remote/app/src/views/library/Library.jsx
import { useEffect, useMemo, useRef, useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  useMC, docCreate, docSearch, research, launch, toast,
  kindLabel, docStatusLabel, allTags, filterDocs, allDirs,
} from '../../lib/store.js';
import { mergeModels, DEFAULT_SOLO } from '../../lib/models.js';
import { dictate, speechSupported } from '../../lib/speech.js';
import { ago } from '../../lib/md.js';
import { spring, fadeUp, press } from '../../lib/motion.js';
import Sheet from '../../ui/Sheet.jsx';
import Field from '../../ui/Field.jsx';
import Select from '../../ui/Select.jsx';
import Segmented from '../../ui/Segmented.jsx';
import Button from '../../ui/Button.jsx';
import IconButton from '../../ui/IconButton.jsx';
import Icon from '../../ui/Icon.jsx';
import EmptyState from '../../ui/EmptyState.jsx';

// The document library — one central directory of markdown files living in
// ~/.mission-control/library on the Mac, written by you OR by agents (a
// research agent streams its report straight into a file here). This view is
// the reading room: filter by kind/status/tag, search titles instantly and
// bodies over the wire, and open any doc into its own window.
//
// Kinds carry a colour the whole app speaks: plan = accent green, research =
// mgr violet, note = neutral ink. The maps below hold FULL Tailwind class
// strings (never interpolated) so the JIT actually emits them.

const OTHER = '__other';

const INPUT =
  'glass-soft w-full rounded-xl2 px-3.5 py-2.5 text-[14px] text-ink outline-none transition-colors ' +
  'placeholder:text-ink3 focus:border-accent/60 focus:ring-1 focus:ring-accent/40';

const KIND = {
  plan: { icon: 'plan', text: 'text-accent', ring: 'border-accent/35 bg-accent/12 text-accent', chip: 'border-accent/30 text-accent' },
  research: { icon: 'research', text: 'text-mgr', ring: 'border-mgr/35 bg-mgr/12 text-mgr', chip: 'border-mgr/30 text-mgr' },
  note: { icon: 'note', text: 'text-ink2', ring: 'border-glass-line bg-white/[0.07] text-ink2', chip: 'border-glass-line text-ink3' },
};
const kindOf = (k) => KIND[k] || KIND.note;

const STATUS = {
  draft: 'border-glass-line text-ink3',
  active: 'border-accent/40 text-accent',
  done: 'border-ok/40 text-ok',
  archived: 'border-glass-line text-ink3/70',
};
const statusChip = (s) => STATUS[s] || STATUS.draft;

const KIND_TABS = [
  { value: 'all', label: 'All' },
  { value: 'plan', label: 'Plans' },
  { value: 'research', label: 'Research' },
  { value: 'note', label: 'Notes' },
];
const STATUS_TABS = [
  { value: 'all', label: 'Any status' },
  { value: 'draft', label: 'Draft' },
  { value: 'active', label: 'Working' },
  { value: 'done', label: 'Done' },
  { value: 'archived', label: 'Archived' },
];

const toTags = (s) => (s || '').split(',').map((t) => t.trim()).filter(Boolean);
const fixModel = (f) => (f === 'default' ? '' : f);

// Escape agent-authored snippet text BEFORE wrapping query matches in <mark>:
// the snippet is arbitrary repo/body content and must never reach innerHTML raw.
const ESC = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };
function highlight(snippet, query) {
  const safe = String(snippet).replace(/[&<>"']/g, (c) => ESC[c]);
  const q = (query || '').trim();
  if (!q) return safe;
  const rx = new RegExp('(' + q.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + ')', 'ig');
  return safe.replace(rx, '<mark>$1</mark>');
}
// Tailwind arbitrary-variant styling for the injected <mark> elements.
const MARK = '[&_mark]:rounded-[3px] [&_mark]:bg-accent/30 [&_mark]:px-0.5 [&_mark]:text-accent-bright';

// The host's `preview` is a raw slice of the markdown body. Strip the syntax
// that only means something rendered so a card reads as prose, not source.
function cleanPreview(s) {
  return String(s || '')
    .replace(/^#{1,6}\s+/, '')
    .replace(/\s#{1,6}\s+/g, ' · ')
    .replace(/[`*_>]/g, '')
    .trim();
}

// ---------------------------------------------------------------------------
// Project drop-down shared by the three forms: host-known folders + this
// device's launch history; "Other folder…" reveals the manual path input.

function DirPicker({ dirs, value, onChange, placeholder = '~/path/to/project' }) {
  const [other, setOther] = useState(false);
  const sel = !other && dirs.includes(value) ? value : OTHER;
  return (
    <>
      {dirs.length > 0 && (
        <Select
          value={sel}
          onChange={(v) => {
            if (v === OTHER) {
              setOther(true);
              onChange('');
            } else {
              setOther(false);
              onChange(v);
            }
          }}
          options={[...dirs.map((d) => ({ value: d, label: d })), { value: OTHER, label: 'Other folder…' }]}
          className="font-mono"
          aria-label="Project folder"
        />
      )}
      {(sel === OTHER || !dirs.length) && (
        <input
          value={value}
          onChange={(e) => onChange(e.target.value)}
          placeholder={placeholder}
          className={`${INPUT} mt-2 font-mono text-[13px]`}
        />
      )}
    </>
  );
}

// A textarea with the inset mic button — the topic/goal hero of both agent forms.
function MicArea({ value, onChange, placeholder, rows = 3 }) {
  const ref = useRef(null);
  const [on, setOn] = useState(false);
  useEffect(() => () => ref.current?.stop(), []);
  const toggle = () => {
    if (ref.current) {
      ref.current.stop();
      return;
    }
    const stop = () => {
      ref.current = null;
      setOn(false);
    };
    ref.current = dictate({ base: value, onText: onChange, onEnd: stop, onError: stop });
    setOn(!!ref.current);
  };
  return (
    <div className="relative">
      <textarea
        value={value}
        onChange={(e) => onChange(e.target.value)}
        rows={rows}
        placeholder={placeholder}
        className={`noscroll min-h-[92px] w-full resize-y rounded-xl3 px-4 py-3 pr-14 text-[15px] leading-relaxed text-ink outline-none transition-colors placeholder:text-ink3 ${
          on ? 'glass-soft border-crit/50 ring-1 ring-crit/30' : INPUT
        }`}
      />
      {speechSupported && (
        <motion.button
          {...press}
          onClick={toggle}
          aria-label="Dictate"
          className={`absolute right-2.5 top-2.5 grid h-9 w-9 place-items-center rounded-full border transition-colors ${
            on ? 'border-crit/60 bg-crit/15 text-crit' : 'border-glass-line bg-white/[0.08] text-ink2 hover:text-ink'
          }`}
        >
          {on && <span className="anim-ping absolute inset-0 rounded-full bg-crit/40" />}
          <Icon name="mic" size={16} className="relative" />
        </motion.button>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------

function Card({ d, now, onOpen, snippets, q }) {
  const k = kindOf(d.kind);
  return (
    <motion.button
      layout="position"
      {...press}
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, scale: 0.98 }}
      transition={spring.smooth}
      onClick={() => onOpen?.(d.id)}
      className="glass-soft glass-soft-hover flex flex-col gap-2 rounded-xl3 p-4 text-left transition-colors"
    >
      <div className="flex items-start gap-3">
        <span className={`relative grid h-9 w-9 flex-none place-items-center rounded-xl2 border ${k.ring}`}>
          <Icon name={k.icon} size={17} />
          {d.kind === 'research' && d.status === 'active' && (
            <span className="absolute -right-1 -top-1 flex h-2.5 w-2.5">
              <span className="anim-ping absolute inline-flex h-full w-full rounded-full bg-accent/70" />
              <span className="relative inline-flex h-2.5 w-2.5 rounded-full bg-accent" />
            </span>
          )}
        </span>
        <span className="min-w-0 flex-1">
          <span className="block truncate text-[14.5px] font-semibold leading-tight tracking-tight text-ink">
            {d.title}
          </span>
          {d.subject && <span className={`mt-0.5 block truncate text-[12px] ${k.text}`}>{d.subject}</span>}
        </span>
        <span className={`flex-none rounded-full border px-2 py-px text-[10px] font-medium ${statusChip(d.status)}`}>
          {docStatusLabel(d.status)}
        </span>
      </div>

      {snippets ? (
        <span className="flex flex-col gap-1.5">
          {snippets.slice(0, 3).map((s, i) => (
            <span
              key={i}
              className={`glass-soft line-clamp-2 rounded-lg px-2.5 py-1.5 font-mono text-[11px] leading-relaxed text-ink3 ${MARK}`}
              dangerouslySetInnerHTML={{ __html: highlight(s, q) }}
            />
          ))}
        </span>
      ) : (
        d.preview && <span className="line-clamp-2 text-[12.5px] leading-relaxed text-ink3">{cleanPreview(d.preview)}</span>
      )}

      {(d.tags || []).length > 0 && (
        <span className="flex flex-wrap gap-1.5">
          {d.tags.slice(0, 4).map((t) => (
            <span key={t} className={`rounded-full border px-2 py-px text-[11px] ${k.chip}`}>
              #{t}
            </span>
          ))}
        </span>
      )}

      <span className="tnum mt-0.5 flex flex-wrap items-center gap-x-3 gap-y-1 text-[11.5px] text-ink3">
        {d.folder && (
          <span className="flex items-center gap-1">
            <Icon name="folder" size={12} />
            {d.folder}
          </span>
        )}
        <span>{ago(d.updatedAt, now)}</span>
        {d.words ? <span>{d.words.toLocaleString()} words</span> : null}
        <span className={`rounded-full border px-2 py-px ${d.session ? 'border-mgr/30 text-mgr' : 'border-glass-line text-ink3'}`}>
          {d.session ? 'agent' : 'you'}
        </span>
      </span>
    </motion.button>
  );
}

export default function Library({ onOpen, onClose }) {
  const docs = useMC((s) => s.docs);
  const snapshot = useMC((s) => s.snapshot);
  const link = useMC((s) => s.link);
  const now = useMC((s) => s.now);
  const search = useMC((s) => s.search);
  const lastDir = useMC((s) => s.lastDir);
  const hostModels = useMC((s) => s.models);
  const knownDirs = useMC((s) => s.knownDirs);
  const localDirs = useMC((s) => s.localDirs);

  const models = useMemo(() => mergeModels(hostModels), [hostModels]);
  const modelOptions = useMemo(() => models.map((m) => ({ value: m.flag, label: m.label })), [models]);
  const dirs = useMemo(() => allDirs(), [knownDirs, localDirs]);

  // Older Mac hosts predate the whole library — they ship no `docs` field at all.
  const hostTooOld = !!snapshot && !('docs' in snapshot);

  const [kindFilter, setKindFilter] = useState('all');
  const [statusFilter, setStatusFilter] = useState('all');
  const [tagFilter, setTagFilter] = useState('all');
  const [q, setQ] = useState('');

  const tags = useMemo(() => allTags(docs), [docs]);

  // Instant local sieve over the metadata every card already shows.
  const localDocs = useMemo(
    () => filterDocs(docs, { kind: kindFilter, status: statusFilter, tag: tagFilter, q }),
    [docs, kindFilter, statusFilter, tagFilter, q],
  );

  // Kind chip counts respect the OTHER active filters (status/tag/query) so a
  // count reads as "how many I'd see if I picked this kind", not a raw total.
  const kindTabs = useMemo(
    () =>
      KIND_TABS.map((t) => ({
        ...t,
        count: filterDocs(docs, { kind: t.value, status: statusFilter, tag: tagFilter, q }).length,
      })),
    [docs, statusFilter, tagFilter, q],
  );

  // Full-text body search over the wire, debounced. The host answers into
  // mc.search; we only trust a result whose `q` still matches what's typed, so a
  // slow reply for an old query can never clobber the current one.
  useEffect(() => {
    const query = q.trim();
    if (query.length < 2 || link !== 'linked') return undefined;
    const t = setTimeout(() => docSearch(query), 350);
    return () => clearTimeout(t);
  }, [q, link]);

  // Docs the local sieve missed but the host found deep in a body. Only shown
  // for the CURRENT query, and never duplicating a card already on screen.
  const bodyHits = useMemo(() => {
    const query = q.trim();
    if (query.length < 2 || !search || search.q !== query) return [];
    const shown = new Set(localDocs.map((d) => d.id));
    const out = [];
    for (const hit of search.hits || []) {
      if (shown.has(hit.id)) continue;
      const meta = docs.find((d) => d.id === hit.id);
      if (meta) out.push({ meta, snippets: hit.snippets || [] });
    }
    return out;
  }, [q, search, localDocs, docs]);

  // ---- new document ---------------------------------------------------------
  const [creating, setCreating] = useState(false);
  const [nTitle, setNTitle] = useState('');
  const [nKind, setNKind] = useState('note');
  const [nSubject, setNSubject] = useState('');
  const [nTags, setNTags] = useState('');
  const [nDir, setNDir] = useState('');

  function openCreate() {
    setNTitle('');
    setNKind('note');
    setNSubject('');
    setNTags('');
    setNDir(lastDir || '');
    setCreating(true);
  }
  function submitCreate() {
    const title = nTitle.trim() || `Untitled ${kindLabel(nKind).toLowerCase()}`;
    // Created on the Mac; the docCreate ack carries the id and the shell opens
    // it in the editor (a hand-made doc is empty — you type into it now).
    if (!docCreate({ title, kind: nKind, subject: nSubject.trim(), tags: toTags(nTags), dir: nDir.trim() })) return;
    setCreating(false);
  }

  // ---- research -------------------------------------------------------------
  // One agent researches a topic and writes its report straight into a new
  // library file; you read it here as it lands.
  const [researching, setResearching] = useState(false);
  const [rTopic, setRTopic] = useState('');
  const [rSubject, setRSubject] = useState('');
  const [rTags, setRTags] = useState('');
  const [rDir, setRDir] = useState('');
  const [rModel, setRModel] = useState(DEFAULT_SOLO);

  function openResearch() {
    setRDir((d) => d || lastDir || '');
    setResearching(true);
  }
  function launchResearch() {
    const topic = rTopic.trim();
    if (!topic) return toast('What should the agent research?');
    if (!research({ topic, subject: rSubject.trim(), dir: rDir.trim(), model: fixModel(rModel), tags: toTags(rTags) }))
      return;
    setResearching(false);
    setRTopic('');
    setRSubject('');
    setRTags('');
    toast('Research agent launched — its report lands here');
  }

  // ---- draft a plan with an agent -------------------------------------------
  // A read-only planning agent explores the project and presents a plan with
  // ExitPlanMode; the Mac captures that plan into the library automatically.
  const [drafting, setDrafting] = useState(false);
  const [goal, setGoal] = useState('');
  const [dDir, setDDir] = useState('');
  const [dModel, setDModel] = useState(DEFAULT_SOLO);

  function openDraft() {
    setDDir((d) => d || lastDir || '');
    setDrafting(true);
  }
  function draftMission(g) {
    return (
      'Research this project and draft a thorough implementation plan for the goal below. Do NOT write any code — you are in plan mode. ' +
      'Explore the codebase first, then produce one complete, well-structured markdown plan: a clear title as a # heading, context, a concrete step-by-step approach naming the exact files to touch, risks, and how to verify. ' +
      'Present the finished plan with ExitPlanMode — Mission Control saves it to the library automatically.\n\nGOAL: ' +
      g
    );
  }
  function launchDraft() {
    const g = goal.trim();
    if (!g) return toast('Describe what to plan first');
    if (!launch({ mission: draftMission(g), dir: dDir.trim(), managerModel: null, workerModels: [fixModel(dModel)], planMode: true }))
      return;
    setDrafting(false);
    setGoal('');
    toast('Planning agent launched — its plan lands here when ready');
  }

  const total = docs.length;

  return (
    // Container queries, not viewport ones: App can park this list in a 360px
    // column beside an open doc, where a viewport-sized `xl:grid-cols-3` would
    // shred it.
    <div className="@container flex min-h-0 flex-1 flex-col">
      {/* own header — this window is chromeless */}
      <header className="flex flex-none flex-wrap items-center gap-2 px-4 pb-3 pt-4 sm:px-5">
        <h2 className="display mr-auto flex items-baseline gap-2 text-[20px] font-semibold tracking-tight text-ink">
          Library
          {total > 0 && <span className="tnum text-[13px] font-normal text-ink3">{total}</span>}
        </h2>
        <Button size="sm" icon="research" onClick={openResearch}>
          Research
        </Button>
        {/* A display utility on the Button itself would lose to its own
            `inline-flex` base class, so the breakpoint lives on a wrapper. */}
        <span className="hidden @lg:inline-flex">
          <Button size="sm" icon="bolt" onClick={openDraft}>
            Draft plan
          </Button>
        </span>
        <Button size="sm" variant="primary" icon="plus" onClick={openCreate}>
          New
        </Button>
        {onClose && <IconButton icon="close" label="Close" size="sm" variant="glass" onClick={onClose} />}
      </header>

      {hostTooOld ? (
        <EmptyState
          icon="alert"
          title="Your Mac app is out of date"
          hint="The document library lives on your Mac. Rebuild and relaunch Mission Control there to start syncing plans, research, and notes."
        />
      ) : (
        <>
          {/* one control row: search · kind · status */}
          <div className="flex flex-none flex-wrap items-center gap-2 px-4 pb-3 sm:px-5">
            <div className="relative min-w-[200px] flex-1 sm:max-w-xs">
              <Icon
                name="search"
                size={15}
                className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-ink3"
              />
              <input
                value={q}
                onChange={(e) => setQ(e.target.value)}
                placeholder="Search titles and full text…"
                className="glass-soft h-10 w-full rounded-full pl-9 pr-9 text-[13.5px] text-ink outline-none transition-colors placeholder:text-ink3 focus:border-accent/60 focus:ring-1 focus:ring-accent/40"
              />
              {q.trim() && (
                <button
                  onClick={() => setQ('')}
                  aria-label="Clear search"
                  className="absolute right-2 top-1/2 grid h-7 w-7 -translate-y-1/2 place-items-center rounded-full text-ink3 transition-colors hover:bg-white/10 hover:text-ink2"
                >
                  <Icon name="close" size={14} />
                </button>
              )}
            </div>
            <Segmented options={kindTabs} value={kindFilter} onChange={setKindFilter} />
            <Select
              options={STATUS_TABS}
              value={statusFilter}
              onChange={setStatusFilter}
              className="w-[132px]"
              aria-label="Status filter"
            />
          </div>

          {tags.length > 0 && (
            <div className="noscroll flex flex-none gap-1.5 overflow-x-auto px-4 pb-3 sm:px-5">
              {tags.map((t) => (
                <motion.button
                  key={t}
                  {...press}
                  onClick={() => setTagFilter((cur) => (cur === t ? 'all' : t))}
                  className={`pill flex-none border px-3 py-1 text-[12px] transition-colors ${
                    tagFilter === t
                      ? 'border-accent/40 bg-accent/12 text-accent'
                      : 'border-glass-line bg-white/[0.05] text-ink3 hover:text-ink2'
                  }`}
                >
                  #{t}
                </motion.button>
              ))}
            </div>
          )}

          {/* Below 1024 the window is a full-screen sheet with the dock
              floating over it — the last card must clear the dock. */}
          <div className="noscroll min-h-0 flex-1 overflow-y-auto px-4 pb-28 sm:px-5 lg:pb-8">
            {!total ? (
              <EmptyState
                icon="library"
                title="Your library is empty"
                hint="A folder of markdown files (~/.mission-control/library) on your Mac — written by you or by agents, readable from anywhere. Send an agent to research a topic, draft a plan, or start a note by hand."
                action={
                  <Button variant="primary" icon="research" onClick={openResearch}>
                    Research something
                  </Button>
                }
              />
            ) : !localDocs.length && !bodyHits.length ? (
              <EmptyState icon="search" title="Nothing matches" hint="Try a different kind, status, tag, or search term." />
            ) : (
              <>
                {localDocs.length > 0 && (
                  <motion.div
                    layout
                    className="grid grid-cols-1 gap-3 @2xl:grid-cols-2 @5xl:grid-cols-3"
                  >
                    <AnimatePresence initial={false} mode="popLayout">
                      {localDocs.map((d) => (
                        <Card key={d.id} d={d} now={now} onOpen={onOpen} />
                      ))}
                    </AnimatePresence>
                  </motion.div>
                )}

                {bodyHits.length > 0 && (
                  <>
                    <div className="mb-3 mt-6 flex items-baseline gap-2">
                      <h3 className="text-[12.5px] font-semibold text-ink2">Found in body</h3>
                      <span className="tnum text-[12.5px] text-ink3">{bodyHits.length}</span>
                    </div>
                    <div className="grid grid-cols-1 gap-3 @2xl:grid-cols-2 @5xl:grid-cols-3">
                      {bodyHits.map((h) => (
                        <Card key={h.meta.id} d={h.meta} now={now} onOpen={onOpen} snippets={h.snippets} q={q} />
                      ))}
                    </div>
                  </>
                )}
              </>
            )}
          </div>
        </>
      )}

      {/* ---- new document ---------------------------------------------------- */}
      <Sheet
        open={creating}
        onClose={() => setCreating(false)}
        title="New document"
        size="sm"
        footer={
          <div className="flex items-center justify-end gap-2">
            <Button variant="ghost" onClick={() => setCreating(false)}>
              Cancel
            </Button>
            <Button variant="primary" icon="plus" onClick={submitCreate}>
              Create
            </Button>
          </div>
        }
      >
        <div className="flex flex-col gap-4 pt-1">
          <Field label="Title">
            <input
              value={nTitle}
              onChange={(e) => setNTitle(e.target.value)}
              placeholder={`Untitled ${kindLabel(nKind).toLowerCase()}`}
              className={INPUT}
            />
          </Field>
          <div>
            <span className="label mb-1.5 block">Kind</span>
            <Segmented
              value={nKind}
              onChange={setNKind}
              options={[
                { value: 'plan', label: 'Plan', icon: 'plan' },
                { value: 'research', label: 'Research', icon: 'research' },
                { value: 'note', label: 'Note', icon: 'note' },
              ]}
            />
            <p className="mt-2 text-[12px] leading-snug text-ink3">
              {nKind === 'plan'
                ? 'A build plan you can hand to a fleet.'
                : nKind === 'research'
                  ? 'A research file — or send an agent to write one for you.'
                  : 'A free-form note to keep.'}
            </p>
          </div>
          <Field label="Subject">
            <input
              value={nSubject}
              onChange={(e) => setNSubject(e.target.value)}
              placeholder="Company, project, person (optional)"
              className={INPUT}
            />
          </Field>
          <Field label="Tags">
            <input
              value={nTags}
              onChange={(e) => setNTags(e.target.value)}
              placeholder="comma, separated (optional)"
              className={INPUT}
            />
          </Field>
          <Field label="Project">
            <DirPicker dirs={dirs} value={nDir} onChange={setNDir} placeholder="~/path/to/project (optional)" />
          </Field>
        </div>
      </Sheet>

      {/* ---- research -------------------------------------------------------- */}
      <Sheet
        open={researching}
        onClose={() => setResearching(false)}
        title="Research with an agent"
        size="md"
        footer={
          <div className="flex items-center gap-3">
            <p className="min-w-0 flex-1 text-[12px] leading-snug text-ink3">
              One agent researches and writes its report straight into the library.
            </p>
            <Button variant="primary" icon="research" onClick={launchResearch} className="flex-none">
              Research
            </Button>
          </div>
        }
      >
        <div className="flex flex-col gap-4 pt-1">
          <MicArea value={rTopic} onChange={setRTopic} placeholder="What should the agent research?" />
          <Field label="Subject">
            <input
              value={rSubject}
              onChange={(e) => setRSubject(e.target.value)}
              placeholder="Subject / company (optional)"
              className={INPUT}
            />
          </Field>
          <Field label="Tags">
            <input
              value={rTags}
              onChange={(e) => setRTags(e.target.value)}
              placeholder="comma, separated (optional)"
              className={INPUT}
            />
          </Field>
          <Field label="Project">
            <DirPicker dirs={dirs} value={rDir} onChange={setRDir} placeholder="~/path/to/project (optional)" />
          </Field>
          <Field label="Model">
            <Select options={modelOptions} value={rModel} onChange={setRModel} aria-label="Research model" />
          </Field>
        </div>
      </Sheet>

      {/* ---- draft a plan with an agent -------------------------------------- */}
      <Sheet
        open={drafting}
        onClose={() => setDrafting(false)}
        title="Draft a plan with an agent"
        size="md"
        footer={
          <div className="flex items-center gap-3">
            <p className="min-w-0 flex-1 text-[12px] leading-snug text-ink3">
              Read-only plan mode — nothing gets built until you say so.
            </p>
            <Button variant="primary" icon="bolt" onClick={launchDraft} className="flex-none">
              Draft
            </Button>
          </div>
        }
      >
        <div className="flex flex-col gap-4 pt-1">
          <MicArea value={goal} onChange={setGoal} placeholder="What should the plan achieve?" />
          <Field label="Project">
            <DirPicker dirs={dirs} value={dDir} onChange={setDDir} />
          </Field>
          <Field label="Model">
            <Select options={modelOptions} value={dModel} onChange={setDModel} aria-label="Planning model" />
          </Field>
        </div>
      </Sheet>
    </div>
  );
}
