// remote/panel/src/components/Launch.svelte
<script>
  import { onDestroy } from 'svelte';
  import { mc, launch, toast, kindLabel } from '../lib/store.svelte.js';
  import { dictate, speechSupported } from '../lib/speech.js';
  import Icon from './Icon.svelte';

  let { onclose, attachDoc = null } = $props();

  // A library document riding along with this launch: a plan to BUILD, or a
  // research/note to CONTINUE. `mode` ('build' | 'continue') tells the Mac how to
  // frame it; it folds the doc's content and file path into the mission, so the
  // doc can stand in for missing mission text and supplies a default working dir.
  let doc = $state(attachDoc);

  const DOC_TONE = {
    plan: { icon: 'plan', text: 'text-accent', edge: 'border-accent/40 bg-accent/8' },
    research: { icon: 'research', text: 'text-mgr', edge: 'border-mgr/40 bg-mgr/8' },
    note: { icon: 'note', text: 'text-ink2', edge: 'border-line2 bg-raised/50' },
  };
  const docTone = $derived(DOC_TONE[doc?.kind] || DOC_TONE.note);
  const docVerb = $derived(doc?.mode === 'continue' ? 'Continuing' : 'Building');

  const FALLBACK = [
    { flag: 'claude-fable-5', label: 'Fable 5', short: 'Fable', blurb: 'Frontier intelligence — the apex model' },
    { flag: 'opus', label: 'Opus 4.8', short: 'Opus', blurb: 'Deepest reasoning — the heavy lifter' },
    { flag: 'claude-sonnet-5', label: 'Sonnet 5', short: 'Sonnet', blurb: 'Near-Opus smarts at Sonnet speed' },
    { flag: 'haiku', label: 'Haiku 4.5', short: 'Haiku', blurb: 'Fast & cheap — quick passes' },
    { flag: 'default', label: 'Default', short: 'Default', blurb: 'Whatever your CLI defaults to' },
  ];
  const models = $derived(mc.models.length ? mc.models : FALLBACK);

  let mode = $state('fleet');
  let mission = $state('');
  let dir = $state('');
  let soloModel = $state('opus');
  let managerModel = $state('opus');
  let workers = $state(['claude-sonnet-5', 'claude-sonnet-5']);

  let dirTouched = false;
  $effect(() => {
    if (!dirTouched && !dir && (doc?.dir || mc.lastDir)) dir = doc?.dir || mc.lastDir;
  });

  // Snap model choices onto the host's actual list — a default flag that the
  // connected Mac doesn't offer would otherwise render as an empty select.
  $effect(() => {
    const flags = new Set(models.map((m) => m.flag));
    const pick = (want) => models.find((m) => m.flag.includes(want))?.flag || models[0]?.flag || '';
    if (!flags.has(soloModel)) soloModel = pick('opus');
    if (!flags.has(managerModel)) managerModel = pick('opus');
    if (workers.some((w) => !flags.has(w))) workers = workers.map((w) => (flags.has(w) ? w : pick('sonnet')));
  });

  const agentCount = $derived(mode === 'solo' ? 1 : 1 + workers.length);
  // "Other folder…" input only shows when the current dir isn't one of the chips.
  const knownDir = $derived(mc.knownDirs.includes(dir));
  let showDirInput = $state(false);

  // dictation for the mission field
  let micSession = $state(null);
  function toggleMic() {
    if (micSession) {
      micSession.stop();
      return;
    }
    micSession = dictate({ base: mission, onText: (t) => (mission = t), onEnd: () => (micSession = null), onError: () => (micSession = null) });
  }

  function step(d) {
    if (d > 0 && workers.length < 8) workers = [...workers, workers[workers.length - 1] || 'claude-sonnet-5'];
    if (d < 0 && workers.length > 1) workers = workers.slice(0, -1);
  }

  // Per-worker model rows are advanced detail — one shared select covers the
  // common case, the list unfolds on demand.
  let perWorker = $state(false);
  function setAllWorkers(flag) {
    workers = workers.map(() => flag);
  }
  const workersUniform = $derived(new Set(workers).size <= 1);

  // The launch overlay is driven by the user's click (optimistic), NOT by a
  // persisted ack — a leftover ack must never re-fire when the sheet reopens.
  let launching = $state(false);
  let launchMsg = $state('Launching…');
  let timers = [];
  onDestroy(() => timers.forEach(clearTimeout));

  function doLaunch() {
    const m = mission.trim();
    if (!m && !doc) return toast('Describe the mission first');
    if (mode === 'fleet' && workers.length === 0) return toast('Add at least one worker');
    const fix = (f) => (f === 'default' ? '' : f);
    const payload =
      mode === 'solo'
        ? { mission: m, dir: dir.trim(), managerModel: null, workerModels: [fix(soloModel)] }
        : { mission: m, dir: dir.trim(), managerModel: fix(managerModel) || 'opus', workerModels: workers.map(fix) };
    if (doc) {
      payload.docId = doc.id;
      payload.docMode = doc.mode || (doc.kind === 'plan' ? 'build' : 'continue');
    }
    if (!launch(payload)) return; // send() already toasted the reason
    mission = '';
    launching = true;
    launchMsg = 'Launching…';
    timers.forEach(clearTimeout);
    timers = [
      setTimeout(() => (launchMsg = 'Deployed — agents incoming'), 1400),
      setTimeout(() => {
        launching = false;
        onclose('fleet');
      }, 2400),
    ];
  }
</script>

<div class="fixed inset-0 z-[70] flex flex-col bg-bg">
  <header class="flex flex-none items-center gap-3 border-b border-line bg-surface/85 px-4 backdrop-blur sm:px-6" style="padding-top:calc(12px + var(--sat));padding-bottom:12px">
    <button onclick={() => onclose()} aria-label="Close" class="grid h-10 w-10 flex-none place-items-center rounded-xl text-ink2 transition hover:bg-raised"><Icon name="close" size={22} /></button>
    <h2 class="text-[18px] font-semibold leading-none tracking-tight">Launch</h2>
  </header>

  <main class="min-h-0 flex-1 overflow-y-auto noscroll">
    <div class="mx-auto flex max-w-[680px] flex-col gap-6 p-4 pb-8 sm:p-6">
      <!-- THE MISSION — the hero. Everything else is a detail. -->
      <section>
        {#if doc}
          <div class="mb-3 flex items-center gap-3 rounded-xl border {docTone.edge} px-3.5 py-2.5">
            <Icon name={docTone.icon} size={17} class="flex-none {docTone.text}" />
            <div class="min-w-0 flex-1">
              <div class="truncate text-[13.5px] font-semibold {docTone.text}">{doc.title}</div>
              <div class="mt-0.5 text-[11.5px] text-ink3">{docVerb} this {kindLabel(doc.kind).toLowerCase()} — sent to the agents with the mission</div>
            </div>
            <button onclick={() => (doc = null)} aria-label="Detach document" class="grid h-9 w-9 flex-none place-items-center rounded-lg text-ink3 transition hover:text-crit"><Icon name="close" size={16} /></button>
          </div>
        {/if}
        <div class="relative">
          <textarea
            bind:value={mission}
            rows="4"
            placeholder={doc ? 'Optional extra instructions — the document is the mission…' : 'What should get done?'}
            class="min-h-32 w-full resize-y rounded-2xl border bg-inset px-5 py-4 pr-14 text-[17px] leading-relaxed text-ink outline-none transition placeholder:text-ink3 noscroll {micSession ? 'border-crit/40' : 'border-line focus:border-line2'}"></textarea>
          {#if speechSupported}
            <button
              onclick={toggleMic}
              aria-label="Dictate mission"
              class="absolute right-3 top-3 grid h-10 w-10 place-items-center rounded-xl border transition active:scale-95 {micSession ? 'border-crit bg-crit/12 text-crit' : 'border-line bg-raised/80 text-ink2'}"
              style={micSession ? 'animation:mc-ring 1.4s ease-out infinite' : ''}><Icon name="mic" size={18} /></button>
          {/if}
        </div>
      </section>

      <!-- WHERE -->
      <section>
        <div class="hud mb-2">Project</div>
        <div class="flex flex-wrap gap-1.5">
          {#each mc.knownDirs as d (d)}
            <button
              onclick={() => { dir = d; dirTouched = true; showDirInput = false; }}
              class="flex min-h-[40px] items-center gap-1.5 rounded-xl border px-3.5 text-[13.5px] transition active:scale-95 {d === dir ? 'border-line2 bg-raised font-medium text-ink' : 'border-line text-ink2 hover:border-line2'}">
              <Icon name="folder" size={14} class={d === dir ? 'text-ink2' : 'text-ink3'} />
              {d.split('/').filter(Boolean).pop() || d}
            </button>
          {/each}
          <button
            onclick={() => (showDirInput = !showDirInput)}
            class="min-h-[40px] rounded-xl border px-3.5 text-[13.5px] transition active:scale-95 {showDirInput || (dir && !knownDir) ? 'border-line2 bg-raised text-ink' : 'border-line text-ink3 hover:border-line2'}">
            Other…
          </button>
        </div>
        {#if showDirInput || (dir && !knownDir)}
          <input bind:value={dir} oninput={() => (dirTouched = true)} placeholder="~/path/to/project" class="mt-2 w-full rounded-xl border border-line bg-inset px-4 py-3 font-mono text-[13px] text-ink outline-none transition placeholder:text-ink3 focus:border-line2" />
        {/if}
      </section>

      <!-- WHO -->
      <section>
        <div class="hud mb-2">Team</div>
        <div class="flex flex-wrap items-center gap-2">
          <div class="flex overflow-hidden rounded-xl border border-line">
            {#each [['solo', 'Solo'], ['fleet', 'Fleet']] as [m, label] (m)}
              <button onclick={() => (mode = m)} class="min-h-[42px] px-5 text-[14px] font-medium transition {mode === m ? 'bg-raised text-ink' : 'text-ink3 hover:text-ink2'}">{label}</button>
            {/each}
          </div>
          {#if mode === 'fleet'}
            <div class="flex items-center gap-1 rounded-xl border border-line px-1.5 py-1">
              <button onclick={() => step(-1)} aria-label="Fewer workers" class="grid h-8 w-9 place-items-center rounded-lg text-[17px] text-ink2 transition hover:bg-raised active:scale-95">−</button>
              <span class="w-[76px] text-center text-[13.5px] tabular-nums text-ink2"><b class="text-ink">{workers.length}</b> worker{workers.length === 1 ? '' : 's'}</span>
              <button onclick={() => step(1)} aria-label="More workers" class="grid h-8 w-9 place-items-center rounded-lg text-[17px] text-ink2 transition hover:bg-raised active:scale-95">+</button>
            </div>
            <span class="text-[12.5px] text-ink3">+ 1 manager to run them</span>
          {/if}
        </div>
        {#if mode === 'solo'}
          <p class="mt-2 text-[12.5px] text-ink3">One agent takes the whole task itself.</p>
        {:else}
          <p class="mt-2 text-[12.5px] text-ink3">A manager splits the mission into assignments and reconciles the results.</p>
        {/if}
      </section>

      <!-- WITH WHAT -->
      <section>
        <div class="hud mb-2">{mode === 'solo' ? 'Model' : 'Models'}</div>
        {#if mode === 'solo'}
          <div class="grid grid-cols-2 gap-2 sm:grid-cols-3">
            {#each models as m (m.flag)}
              <button onclick={() => (soloModel = m.flag)} class="flex flex-col gap-1 rounded-xl border p-3.5 text-left transition active:scale-[0.97] {m.flag === soloModel ? 'border-line2 bg-raised' : 'border-line hover:border-line2'}">
                <span class="text-[14px] font-semibold {m.flag === soloModel ? 'text-ink' : 'text-ink2'}">{m.short}</span>
                <span class="text-[12px] leading-snug text-ink3">{m.blurb}</span>
              </button>
            {/each}
          </div>
        {:else}
          <div class="flex flex-col gap-2">
            <label class="flex items-center gap-3">
              <span class="w-[72px] flex-none text-[13px] text-ink3">Manager</span>
              <select bind:value={managerModel} class="min-h-[42px] min-w-0 flex-1 rounded-xl border border-line bg-raised px-3.5 text-[14px] text-ink outline-none transition focus:border-line2">
                {#each models as m (m.flag)}<option value={m.flag}>{m.label}</option>{/each}
              </select>
            </label>
            {#if !perWorker}
              <label class="flex items-center gap-3">
                <span class="w-[72px] flex-none text-[13px] text-ink3">Workers</span>
                <select
                  value={workersUniform ? workers[0] : ''}
                  onchange={(e) => setAllWorkers(e.currentTarget.value)}
                  class="min-h-[42px] min-w-0 flex-1 rounded-xl border border-line bg-raised px-3.5 text-[14px] text-ink outline-none transition focus:border-line2">
                  {#if !workersUniform}<option value="" disabled>Mixed…</option>{/if}
                  {#each models as m (m.flag)}<option value={m.flag}>{m.label}</option>{/each}
                </select>
              </label>
              <button onclick={() => (perWorker = true)} class="self-start text-[12.5px] text-ink3 underline decoration-line2 underline-offset-2 transition hover:text-ink2">Pick a model per worker</button>
            {:else}
              {#each workers as w, i (i)}
                <label class="flex items-center gap-3">
                  <span class="w-[72px] flex-none font-mono text-[12px] tabular-nums text-ink3">Worker {i + 1}</span>
                  <select value={w} onchange={(e) => (workers[i] = e.currentTarget.value)} class="min-h-[42px] min-w-0 flex-1 rounded-xl border border-line bg-raised px-3.5 text-[14px] text-ink outline-none transition focus:border-line2">
                    {#each models as m (m.flag)}<option value={m.flag}>{m.label}</option>{/each}
                  </select>
                </label>
              {/each}
              <button onclick={() => { perWorker = false; setAllWorkers(workers[0]); }} class="self-start text-[12.5px] text-ink3 underline decoration-line2 underline-offset-2 transition hover:text-ink2">Use one model for all workers</button>
            {/if}
          </div>
        {/if}
      </section>
    </div>
  </main>

  <!-- always-visible launch bar -->
  <footer class="flex-none border-t border-line bg-surface/85 px-4 backdrop-blur-xl sm:px-6" style="padding-top:10px;padding-bottom:calc(12px + var(--sab))">
    <div class="mx-auto flex max-w-[680px] items-center gap-4">
      <div class="min-w-0 flex-1 text-[12.5px] leading-snug text-ink3">
        {mode === 'solo' ? '1 agent' : `${agentCount} agents`} · opens in your terminal on the Mac and appears on the board automatically
      </div>
      <button onclick={doLaunch} class="flex h-12 flex-none items-center gap-2 rounded-xl bg-ink px-7 text-[15px] font-semibold text-bg transition active:scale-[0.98]">
        <Icon name="launch" size={17} /> Launch
      </button>
    </div>
  </footer>
</div>

{#if launching}
  <div class="fixed inset-0 z-[90] flex flex-col items-center justify-center gap-6 bg-bg/95 backdrop-blur-sm">
    <div class="relative grid h-16 w-16 place-items-center">
      <div class="absolute inset-0 rounded-full border-2 border-line2 border-t-accent" style="animation:mc-spin .9s linear infinite"></div>
    </div>
    <div class="px-6 text-center">
      <div class="text-[17px] font-semibold {launchMsg.startsWith('Deployed') ? 'text-ok' : 'text-ink'}">{launchMsg}</div>
    </div>
  </div>
{/if}

// remote/app/src/views/launch/Launch.jsx
import { useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { motion, AnimatePresence } from 'motion/react';
import { useMC, launch, toast, kindLabel, allDirs } from '../../lib/store.js';
import { mergeModels, DEFAULT_SOLO, DEFAULT_MANAGER, DEFAULT_WORKER } from '../../lib/models.js';
import { dictate, speechSupported } from '../../lib/speech.js';
import { spring, fadeUp, fadeIn, press } from '../../lib/motion.js';
import Sheet from '../../ui/Sheet.jsx';
import Field from '../../ui/Field.jsx';
import Select from '../../ui/Select.jsx';
import Segmented from '../../ui/Segmented.jsx';
import Button from '../../ui/Button.jsx';
import Icon from '../../ui/Icon.jsx';

// The launch sheet: one mission, one project, who runs it, with what.
// Everything below the mission box is a detail — the textarea is the hero.
// This view owns its own overlay (the Sheet primitive) — App renders it bare.
//
// A library document can ride along: a plan to BUILD, or a research/note to
// CONTINUE. `docMode` tells the Mac how to frame it; the host folds the doc's
// content and file path into the mission, so the doc can stand in for missing
// mission text and supplies a default working dir.

const OTHER = '__other';
const MAX_WORKERS = 8;

// Glass form field — soft white fill, 12% hairline, accent focus ring.
const INPUT =
  'glass-soft w-full rounded-xl2 px-3.5 py-2.5 text-[14px] text-ink outline-none transition-colors ' +
  'placeholder:text-ink3 focus:border-accent/60 focus:ring-1 focus:ring-accent/40';

const DOC_TONE = {
  plan: { icon: 'plan', text: 'text-accent', edge: 'border-accent/35 bg-accent/[0.09]' },
  research: { icon: 'research', text: 'text-mgr', edge: 'border-mgr/35 bg-mgr/[0.09]' },
  note: { icon: 'note', text: 'text-ink2', edge: 'border-glass-line bg-white/[0.06]' },
};

export default function Launch({ attachDoc = null, onClose }) {
  // The attached doc is local state — it can be detached without closing.
  const [doc, setDoc] = useState(attachDoc);
  useEffect(() => setDoc(attachDoc), [attachDoc]);

  const hostModels = useMC((s) => s.models);
  const models = useMemo(() => mergeModels(hostModels), [hostModels]);
  const lastDir = useMC((s) => s.lastDir);
  // allDirs() reads the store imperatively — subscribe to both slices it folds
  // together so the picker re-renders when either moves.
  const knownDirs = useMC((s) => s.knownDirs);
  const localDirs = useMC((s) => s.localDirs);
  const dirs = useMemo(() => allDirs(), [knownDirs, localDirs]);

  const [mode, setMode] = useState('fleet');
  const [mission, setMission] = useState('');
  const [dir, setDir] = useState('');
  const [soloModel, setSoloModel] = useState(DEFAULT_SOLO);
  const [managerModel, setManagerModel] = useState(DEFAULT_MANAGER);
  const [workers, setWorkers] = useState([DEFAULT_WORKER, DEFAULT_WORKER]);

  // Default the working dir once — from the attached doc, else the last launch.
  // A user edit sticks: `dirTouched` keeps the default from creeping back.
  const dirTouched = useRef(false);
  useEffect(() => {
    if (dirTouched.current || dir) return;
    const want = doc?.dir || lastDir;
    if (want) setDir(want);
  }, [dir, doc, lastDir]);

  // Snap model choices onto the host's actual list — a default flag that the
  // connected Mac doesn't offer would otherwise render as an empty select.
  // (mergeModels keeps every KNOWN flag present, so this is the safety net for
  // a host that advertises a list with nothing familiar in it.)
  useEffect(() => {
    if (!models.length) return;
    const flags = new Set(models.map((m) => m.flag));
    const pick = (want) => models.find((m) => m.flag.includes(want))?.flag || models[0].flag;
    if (!flags.has(soloModel)) setSoloModel(pick('fable'));
    if (!flags.has(managerModel)) setManagerModel(pick('fable'));
    setWorkers((ws) => (ws.some((w) => !flags.has(w)) ? ws.map((w) => (flags.has(w) ? w : pick('sonnet'))) : ws));
  }, [models, soloModel, managerModel]);

  // Labels only: the blurb rides under the solo picker as a caption instead of
  // bloating every option in a native picker.
  const modelOptions = useMemo(() => models.map((m) => ({ value: m.flag, label: m.label })), [models]);
  const soloBlurb = models.find((m) => m.flag === soloModel)?.blurb || '';

  const knownDir = dirs.includes(dir);
  const [showDirInput, setShowDirInput] = useState(false);
  const dirSel = !showDirInput && knownDir ? dir : OTHER;
  const manualDir = dirSel === OTHER || !dirs.length;

  // ---- dictation for the mission field ---------------------------------------
  const [mic, setMic] = useState(null);
  const micRef = useRef(null);
  useEffect(() => () => micRef.current?.stop(), []);
  function toggleMic() {
    if (micRef.current) {
      micRef.current.stop();
      return;
    }
    const stop = () => {
      micRef.current = null;
      setMic(null);
    };
    const s = dictate({ base: mission, onText: setMission, onEnd: stop, onError: stop });
    micRef.current = s;
    setMic(s);
  }

  function step(d) {
    setWorkers((ws) => {
      if (d > 0 && ws.length < MAX_WORKERS) return [...ws, ws[ws.length - 1] || DEFAULT_WORKER];
      if (d < 0 && ws.length > 1) return ws.slice(0, -1);
      return ws;
    });
  }

  // Per-worker model rows are advanced detail — one shared select covers the
  // common case, the list unfolds on demand.
  const [perWorker, setPerWorker] = useState(false);
  const workersUniform = new Set(workers).size <= 1;
  const setAllWorkers = (flag) => setWorkers((ws) => ws.map(() => flag));

  const agentCount = mode === 'solo' ? 1 : 1 + workers.length;

  // The launch overlay is driven by the user's click (optimistic), NOT by a
  // persisted ack — a leftover ack must never re-fire when the sheet reopens.
  const [launching, setLaunching] = useState(false);
  const [launchMsg, setLaunchMsg] = useState('Launching…');
  const timers = useRef([]);
  useEffect(() => () => timers.current.forEach(clearTimeout), []);

  function doLaunch() {
    const m = mission.trim();
    if (!m && !doc) return toast('Describe the mission first');
    if (mode === 'fleet' && workers.length === 0) return toast('Add at least one worker');
    const fix = (f) => (f === 'default' ? '' : f);
    const payload =
      mode === 'solo'
        ? { mission: m, dir: dir.trim(), managerModel: null, workerModels: [fix(soloModel)] }
        : { mission: m, dir: dir.trim(), managerModel: fix(managerModel) || 'opus', workerModels: workers.map(fix) };
    if (doc) {
      payload.docId = doc.id;
      payload.docMode = doc.mode || (doc.kind === 'plan' ? 'build' : 'continue');
    }
    if (!launch(payload)) return; // send() already toasted the reason
    setMission('');
    setLaunching(true);
    setLaunchMsg('Launching…');
    timers.current.forEach(clearTimeout);
    timers.current = [
      setTimeout(() => setLaunchMsg('Deployed — agents incoming'), 1400),
      setTimeout(() => {
        setLaunching(false);
        onClose?.('fleet');
      }, 2400),
    ];
  }

  const tone = DOC_TONE[doc?.kind] || DOC_TONE.note;
  const docVerb = doc?.mode === 'continue' ? 'Continuing' : 'Building';

  const footer = (
    <div className="flex items-center gap-4">
      <p className="min-w-0 flex-1 text-[12px] leading-snug text-ink3">
        {agentCount === 1 ? '1 agent' : `${agentCount} agents`} · opens in your terminal on the Mac
        <span className="hidden sm:inline"> and appears on the board automatically</span>
      </p>
      <Button variant="primary" size="lg" icon="launch" onClick={doLaunch} className="flex-none">
        Launch
      </Button>
    </div>
  );

  return (
    <>
      <Sheet open onClose={() => onClose?.()} title="Launch" size="md" footer={footer}>
        <div className="flex flex-col gap-5 pt-1">
          {/* THE MISSION — the hero. Everything else is a detail. */}
          <section>
            <AnimatePresence initial={false}>
              {doc && (
                <motion.div
                  {...fadeUp}
                  className={`mb-2.5 flex items-center gap-3 rounded-xl2 border px-3.5 py-2.5 ${tone.edge}`}
                >
                  <Icon name={tone.icon} size={17} className={`flex-none ${tone.text}`} />
                  <div className="min-w-0 flex-1">
                    <div className={`truncate text-[13px] font-semibold ${tone.text}`}>{doc.title}</div>
                    <div className="mt-0.5 text-[11.5px] leading-snug text-ink3">
                      {docVerb} this {kindLabel(doc.kind).toLowerCase()} — sent to the agents with the mission
                    </div>
                  </div>
                  <motion.button
                    {...press}
                    onClick={() => setDoc(null)}
                    aria-label="Detach document"
                    className="grid h-8 w-8 flex-none place-items-center rounded-full text-ink3 transition-colors hover:bg-white/10 hover:text-crit"
                  >
                    <Icon name="close" size={15} />
                  </motion.button>
                </motion.div>
              )}
            </AnimatePresence>

            <div className="relative">
              <textarea
                value={mission}
                onChange={(e) => setMission(e.target.value)}
                rows={4}
                placeholder={doc ? 'Optional extra instructions — the document is the mission…' : 'What should get done?'}
                className={`noscroll min-h-[124px] w-full resize-y rounded-xl3 px-4 py-3.5 pr-14 text-[16px] leading-relaxed text-ink outline-none transition-colors placeholder:text-ink3 ${
                  mic ? 'glass-soft border-crit/50 ring-1 ring-crit/30' : INPUT
                }`}
              />
              {speechSupported && (
                <motion.button
                  {...press}
                  onClick={toggleMic}
                  aria-label="Dictate mission"
                  className={`absolute right-2.5 top-2.5 grid h-10 w-10 place-items-center rounded-full border transition-colors ${
                    mic
                      ? 'border-crit/60 bg-crit/15 text-crit'
                      : 'border-glass-line bg-white/[0.08] text-ink2 hover:text-ink'
                  }`}
                >
                  {mic && <span className="anim-ping absolute inset-0 rounded-full bg-crit/40" />}
                  <Icon name="mic" size={17} className="relative" />
                </motion.button>
              )}
            </div>
          </section>

          {/* WHERE */}
          <Field label="Project">
            {dirs.length > 0 && (
              <Select
                value={dirSel}
                onChange={(v) => {
                  dirTouched.current = true;
                  if (v === OTHER) {
                    setShowDirInput(true);
                    setDir(''); // picking "Other" clears the bound dir
                  } else {
                    setDir(v);
                    setShowDirInput(false);
                  }
                }}
                options={[...dirs.map((d) => ({ value: d, label: d })), { value: OTHER, label: 'Other folder…' }]}
                className="font-mono"
                aria-label="Project folder"
              />
            )}
            {manualDir && (
              <input
                value={dir}
                onChange={(e) => {
                  dirTouched.current = true;
                  setDir(e.target.value);
                }}
                placeholder="~/path/to/project"
                className={`${INPUT} mt-2 font-mono text-[13px]`}
              />
            )}
          </Field>

          {/* WHO */}
          <section>
            <span className="label mb-1.5 block">Team</span>
            <div className="flex flex-wrap items-center gap-2">
              <Segmented
                value={mode}
                onChange={setMode}
                options={[
                  { value: 'solo', label: 'Solo' },
                  { value: 'fleet', label: 'Fleet' },
                ]}
              />
              <AnimatePresence initial={false}>
                {mode === 'fleet' && (
                  <motion.div {...fadeIn} className="glass-soft pill flex items-center gap-1 px-1 py-0.5">
                    <motion.button
                      {...press}
                      onClick={() => step(-1)}
                      aria-label="Fewer workers"
                      disabled={workers.length <= 1}
                      className="grid h-8 w-8 place-items-center rounded-full text-ink2 transition-colors hover:bg-white/10 hover:text-ink disabled:pointer-events-none disabled:opacity-30"
                    >
                      <Icon name="minus" size={15} />
                    </motion.button>
                    <span className="tnum w-[74px] text-center text-[12.5px] text-ink3">
                      <b className="font-semibold text-ink">{workers.length}</b> worker{workers.length === 1 ? '' : 's'}
                    </span>
                    <motion.button
                      {...press}
                      onClick={() => step(1)}
                      aria-label="More workers"
                      disabled={workers.length >= MAX_WORKERS}
                      className="grid h-8 w-8 place-items-center rounded-full text-ink2 transition-colors hover:bg-white/10 hover:text-ink disabled:pointer-events-none disabled:opacity-30"
                    >
                      <Icon name="plus" size={15} />
                    </motion.button>
                  </motion.div>
                )}
              </AnimatePresence>
              {mode === 'fleet' && <span className="text-[12px] text-ink3">+ 1 manager to run them</span>}
            </div>
            <p className="mt-2 text-[12px] leading-snug text-ink3">
              {mode === 'solo'
                ? 'One agent takes the whole task itself.'
                : 'A manager splits the mission into assignments and reconciles the results.'}
            </p>
          </section>

          {/* WITH WHAT */}
          <section>
            <span className="label mb-1.5 block">{mode === 'solo' ? 'Model' : 'Models'}</span>
            <AnimatePresence mode="wait" initial={false}>
              {mode === 'solo' ? (
                <motion.div key="solo" {...fadeUp}>
                  <Select options={modelOptions} value={soloModel} onChange={setSoloModel} aria-label="Model" />
                  {soloBlurb && <p className="mt-2 text-[12px] leading-snug text-ink3">{soloBlurb}</p>}
                </motion.div>
              ) : (
                <motion.div key="fleet" {...fadeUp} className="flex flex-col gap-2">
                  <label className="flex items-center gap-3">
                    <span className="w-[68px] flex-none text-[12.5px] text-ink3">Manager</span>
                    <Select
                      options={modelOptions}
                      value={managerModel}
                      onChange={setManagerModel}
                      className="min-w-0 flex-1"
                      aria-label="Manager model"
                    />
                  </label>
                  {!perWorker ? (
                    <>
                      <label className="flex items-center gap-3">
                        <span className="w-[68px] flex-none text-[12.5px] text-ink3">Workers</span>
                        <Select
                          // A mixed set has no single value — show the sentinel
                          // rather than silently claiming worker 1's model.
                          options={workersUniform ? modelOptions : [{ value: '', label: 'Mixed…' }, ...modelOptions]}
                          value={workersUniform ? workers[0] : ''}
                          onChange={setAllWorkers}
                          className="min-w-0 flex-1"
                          aria-label="Worker model"
                        />
                      </label>
                      <button
                        onClick={() => setPerWorker(true)}
                        className="self-start text-[12px] text-ink3 underline decoration-white/20 underline-offset-2 transition-colors hover:text-ink2"
                      >
                        Pick a model per worker
                      </button>
                    </>
                  ) : (
                    <>
                      {workers.map((w, i) => (
                        <label key={i} className="flex items-center gap-3">
                          <span className="tnum w-[68px] flex-none text-[12px] text-ink3">Worker {i + 1}</span>
                          <Select
                            options={modelOptions}
                            value={w}
                            onChange={(v) => setWorkers((ws) => ws.map((x, j) => (j === i ? v : x)))}
                            className="min-w-0 flex-1"
                            aria-label={`Worker ${i + 1} model`}
                          />
                        </label>
                      ))}
                      <button
                        onClick={() => {
                          setPerWorker(false);
                          setAllWorkers(workers[0]);
                        }}
                        className="self-start text-[12px] text-ink3 underline decoration-white/20 underline-offset-2 transition-colors hover:text-ink2"
                      >
                        Use one model for all workers
                      </button>
                    </>
                  )}
                </motion.div>
              )}
            </AnimatePresence>
          </section>
        </div>
      </Sheet>

      {createPortal(
        <AnimatePresence>
          {launching && (
            <motion.div
              {...fadeIn}
              className="fixed inset-0 z-[110] flex flex-col items-center justify-center gap-6 bg-overlay backdrop-blur-xl"
            >
              <span className="anim-spin h-14 w-14 rounded-full border-2 border-white/15 border-t-accent" />
              <AnimatePresence mode="wait">
                <motion.div
                  key={launchMsg}
                  initial={{ opacity: 0, y: 6 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -6 }}
                  transition={spring.smooth}
                  className={`px-6 text-center text-[17px] font-semibold tracking-tight ${
                    launchMsg.startsWith('Deployed') ? 'text-accent' : 'text-ink'
                  }`}
                >
                  {launchMsg}
                </motion.div>
              </AnimatePresence>
            </motion.div>
          )}
        </AnimatePresence>,
        document.body,
      )}
    </>
  );
}
