// remote/app/src/views/modes/TvMode.jsx
import { useEffect, useMemo, useRef, useState } from 'react';
import { motion, AnimatePresence, useReducedMotion } from 'motion/react';
import {
  useMC,
  counts,
  agentStatus,
  statusLabel,
  agentName,
  attentionList,
  groupFleets,
  fmtTokens,
  fmtInt,
  clockOf,
} from '../../lib/store.js';
import { useAgents, useLink, useNow, useWakeLock } from '../../lib/hooks.js';
import { TONE } from '../../lib/tone.js';
import ModeBackdrop from './ModeBackdrop.jsx';

// TV mode — the ambient wall display. Opened via #tv (Settings → TV mode, or
// just append #tv to the URL on the TV's browser). It is the Home scene with
// the volume turned down: a thin clock, ONE honest sentence about the fleet,
// a constellation of agent chips, and a whisper of recent activity. No
// controls, no cursor, no chrome — a room presence, not a workstation.
//
// Sizing: the root sets font-size from vw and EVERYTHING inside is em-based,
// so the composition holds from a 1080p TV to a 4K panel.
//
// The backdrop is a photograph now, so legibility is the whole job: an extra
// scrim sits between the photo and the type, and every figure is white or a
// status colour — nothing mid-grey on top of a mid-grey forest.

const MAX_CHIPS = 12;

// One sentence about the fleet, in the order a human would ask: is the Mac
// there → does anyone need me → is anything running → what happened.
function fleetSentence({ link, agents, items, c }) {
  if (link === 'offline') return 'Reconnecting to the relay';
  if (link === 'relay') return 'Your Mac is offline';
  if (items.length === 1) {
    const it = items[0];
    return it.kind === 'exited'
      ? `${agentName(it.agent)} exited unexpectedly`
      : `${agentName(it.agent)} is asking a question`;
  }
  if (items.length > 1) {
    return c.working
      ? `${c.working} working · ${items.length} need you`
      : `${items.length} agents need you`;
  }
  if (c.working) return `${c.working} agent${c.working === 1 ? '' : 's'} working · nothing waiting`;
  if (!agents.length) return 'No agents running';
  return `All quiet — ${c.done} finished, nothing waiting`;
}

// A single agent, as small as it can be and still say everything: what state,
// who, what it is doing, how fast, how far.
function AgentChip({ a, waiting }) {
  const st = agentStatus(a);
  const todos = a.todos || [];
  const done = todos.filter((t) => t.status === 'completed').length;
  const pct = todos.length ? (100 * done) / todos.length : 0;
  const tps = Math.round(a.tokensPerSec ?? 0);

  return (
    <motion.div
      layout
      initial={{ opacity: 0, y: 6 }}
      animate={
        waiting
          ? { opacity: 1, y: 0, borderColor: ['rgba(240,180,41,.30)', 'rgba(240,180,41,.75)', 'rgba(240,180,41,.30)'] }
          : { opacity: 1, y: 0 }
      }
      exit={{ opacity: 0, y: -4 }}
      transition={
        waiting
          ? { borderColor: { duration: 2.6, repeat: Infinity, ease: 'easeInOut' }, default: { duration: 0.4 } }
          : { duration: 0.4 }
      }
      className={`relative w-[15em] overflow-hidden rounded-[0.85em] border px-[1.05em] pt-[0.85em] pb-[0.9em] ${
        waiting ? 'border-warn/45 bg-warn/[0.08]' : 'border-glass-line bg-black/35'
      }`}
    >
      <div className="flex items-center gap-[0.6em]">
        <span className="relative flex h-[0.5em] w-[0.5em] flex-none">
          {st === 'working' && (
            <span className="anim-ping absolute inline-flex h-full w-full rounded-full bg-accent opacity-50" />
          )}
          <span className={`relative inline-flex h-[0.5em] w-[0.5em] rounded-full ${TONE[st].dot}`} />
        </span>
        <span className="min-w-0 flex-1 truncate text-[0.95em] font-semibold tracking-tight text-white">
          {agentName(a)}
        </span>
        {tps > 0 ? (
          <span className="tnum flex-none font-mono text-[0.6em] text-accent">{fmtInt(tps)} t/s</span>
        ) : (
          <span className={`flex-none text-[0.6em] font-medium ${TONE[st].text}`}>{statusLabel(st)}</span>
        )}
      </div>
      <div className={`mt-[0.35em] truncate text-[0.7em] ${waiting ? 'text-warn/90' : 'text-white/55'}`}>
        {st === 'exited' ? 'Process exited' : a.activity || '—'}
      </div>
      {/* the 2px thread of progress — the only chrome a chip gets */}
      <div className="absolute inset-x-0 bottom-0 h-[2px] bg-white/10">
        <motion.div
          className={`h-full ${st === 'waiting' ? 'bg-warn' : 'bg-accent'}`}
          initial={false}
          animate={{ width: `${pct}%` }}
          transition={{ duration: 0.8, ease: [0.2, 0.8, 0.2, 1] }}
        />
      </div>
    </motion.div>
  );
}

export default function TvMode({ onClose }) {
  const agents = useAgents();
  const screens = useMC((s) => s.screens);
  const summary = useMC((s) => s.summary);
  const fleets = useMC((s) => s.fleets);
  const activity = useMC((s) => s.activity);
  const link = useLink();
  const now = useNow();
  const reduce = useReducedMotion();

  const c = useMemo(() => counts(agents), [agents]);
  const items = useMemo(() => attentionList(agents), [agents, screens]);
  const sentence = fleetSentence({ link, agents, items, c });

  // ---- clock ----
  const d = new Date(now || Date.now());
  const p = (n) => String(n).padStart(2, '0');
  const hm = `${p(d.getHours())}:${p(d.getMinutes())}`;
  const dateLine = d.toLocaleDateString('en-US', { weekday: 'long', day: 'numeric', month: 'long' });

  const linkInfo =
    link === 'linked'
      ? { word: 'Live', cls: 'text-white/70', dot: 'bg-ok' }
      : link === 'relay'
        ? { word: 'Mac offline', cls: 'text-warn', dot: 'bg-warn' }
        : { word: 'Reconnecting', cls: 'text-crit', dot: 'bg-crit' };

  // ---- the constellation: fleets cluster, solos float ----
  // Needs-you first, then working — a big fleet still has to fit one wall.
  const ORDER = { waiting: 0, exited: 1, working: 2, done: 3 };
  const { groups, solo, overflow } = useMemo(() => {
    const sorted = [...agents].sort((a, b) => (ORDER[agentStatus(a)] ?? 9) - (ORDER[agentStatus(b)] ?? 9));
    const shown = sorted.slice(0, MAX_CHIPS);
    const g = groupFleets(shown, fleets);
    return {
      groups: g.groups.filter((x) => (x.manager ? 1 : 0) + x.workers.length >= 2),
      solo: [...g.solo, ...g.groups.filter((x) => (x.manager ? 1 : 0) + x.workers.length < 2).flatMap((x) => (x.manager ? [x.manager, ...x.workers] : x.workers))],
      overflow: Math.max(0, sorted.length - shown.length),
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [agents, fleets]);

  const recent = useMemo(() => [...activity].slice(-4).reverse(), [activity]);

  // ---- controls: hidden until the pointer moves; the cursor sleeps with them ----
  const [showUi, setShowUi] = useState(false);
  const hideTimer = useRef(null);
  function poke() {
    setShowUi(true);
    clearTimeout(hideTimer.current);
    hideTimer.current = setTimeout(() => setShowUi(false), 3200);
  }
  function fullscreen() {
    if (document.fullscreenElement) document.exitFullscreen?.();
    else document.documentElement.requestFullscreen?.().catch(() => {});
  }

  // Keep the TV awake while the display is up — best effort, Safari may decline.
  useWakeLock(true);

  useEffect(() => {
    const onKey = (e) => e.key === 'Escape' && onClose?.();
    window.addEventListener('keydown', onKey);
    return () => {
      window.removeEventListener('keydown', onKey);
      clearTimeout(hideTimer.current);
    };
  }, [onClose]);

  return (
    <div
      className={`fixed inset-0 z-[75] overflow-hidden ${showUi ? '' : 'cursor-none [&_*]:cursor-none'}`}
      onPointerMove={poke}
      role="presentation"
    >
      {/* The photo, on its own opaque base — a takeover shows nothing of the
          app underneath. Then a legibility layer: the picture is beautiful and
          completely unhelpful behind 60px of thin white type, so the wall gets
          an extra scrim, darkest where the headline sits. */}
      <ModeBackdrop extra={0.12} />
      <div className="absolute inset-0 bg-[radial-gradient(70%_55%_at_50%_45%,rgba(0,0,0,.6),transparent_75%)]" />
      <div className="absolute inset-x-0 top-0 h-[24%] bg-gradient-to-b from-black/55 to-transparent" />
      <div className="absolute inset-x-0 bottom-0 h-[26%] bg-gradient-to-t from-black/60 to-transparent" />

      {/* everything scales off this font-size; the slow orbit guards OLEDs */}
      <motion.div
        animate={reduce ? undefined : { x: [0, 5, -4, -5, 0], y: [0, -4, 5, -5, 0] }}
        transition={reduce ? undefined : { duration: 480, repeat: Infinity, ease: 'easeInOut' }}
        className="relative flex h-full flex-col"
        style={{ fontSize: 'clamp(11px, 1.05vw, 30px)' }}
      >
        {/* ---- header: clock left, link right ------------------------------- */}
        {/* Everything lives on the left: the top-right corner is reserved for
            the pointer-revealed ✕/⛶, which must never land on live text. */}
        <header className="flex-none px-[3.2em] pt-[2.4em]">
          <div className="text-[0.85em] font-medium tracking-tight text-white/65">{dateLine}</div>
          <div className="tnum mt-[0.25em] text-[3.9em] font-light leading-none tracking-tight text-white">{hm}</div>
          <div className={`mt-[0.7em] flex items-center gap-[0.55em] text-[0.75em] font-medium ${linkInfo.cls}`}>
            <span className="relative flex h-[0.45em] w-[0.45em]">
              {link !== 'linked' && (
                <span className={`anim-ping absolute inline-flex h-full w-full rounded-full ${linkInfo.dot} opacity-60`} />
              )}
              <span className={`relative inline-flex h-[0.45em] w-[0.45em] rounded-full ${linkInfo.dot}`} />
            </span>
            {linkInfo.word}
          </div>
        </header>

        {/* ---- centre: the sentence, then the constellation ----------------- */}
        <main className="flex min-h-0 flex-1 flex-col items-center justify-center gap-[2.2em] px-[3.2em] py-[1.2em]">
          <AnimatePresence mode="wait" initial={false}>
            <motion.h1
              key={sentence}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -6 }}
              transition={{ duration: 0.5, ease: [0.2, 0.8, 0.2, 1] }}
              className={`max-w-[26em] text-center text-[2.9em] font-semibold leading-[1.1] tracking-tight ${
                items.length ? 'text-warn' : 'text-white'
              }`}
            >
              {sentence}
            </motion.h1>
          </AnimatePresence>

          {(groups.length > 0 || solo.length > 0) && (
            <div className="flex max-w-[76em] flex-wrap items-start justify-center gap-[1.1em]">
              {groups.map((g) => {
                const members = g.manager ? [g.manager, ...g.workers] : g.workers;
                return (
                  <div
                    key={g.id}
                    className="rounded-[1.1em] border border-mgr/30 px-[0.8em] pb-[0.8em] pt-[0.55em]"
                  >
                    <div className="mb-[0.55em] flex items-center gap-[0.5em] px-[0.2em]">
                      <span className="h-[0.32em] w-[0.32em] rounded-full bg-mgr" />
                      <span className="truncate text-[0.68em] font-medium tracking-tight text-mgr">
                        {g.fleet?.title || g.fleet?.name || g.fleet?.mission || 'Fleet'}
                      </span>
                    </div>
                    <div className="flex flex-wrap gap-[0.7em]">
                      {members.map((a) => (
                        <AgentChip key={a.id} a={a} waiting={agentStatus(a) === 'waiting'} />
                      ))}
                    </div>
                  </div>
                );
              })}
              {solo.map((a) => (
                <AgentChip key={a.id} a={a} waiting={agentStatus(a) === 'waiting'} />
              ))}
              {overflow > 0 && (
                <div className="grid w-[8em] place-items-center rounded-[0.85em] border border-glass-line px-[1em] py-[1.1em] text-[0.72em] text-white/55">
                  +{overflow} more
                </div>
              )}
            </div>
          )}
        </main>

        {/* ---- footer: whispers left, figures right ------------------------- */}
        <footer className="flex flex-none items-end justify-between gap-[3em] px-[3.2em] pb-[2.2em]">
          <div className="min-w-0 flex-1">
            {recent.length > 0 && (
              <div className="space-y-[0.5em]">
                {recent.map((r, i) => (
                  <div
                    key={`${r.t}-${r.id}-${i}`}
                    className="truncate font-mono text-[0.64em] text-white/60"
                    style={{ opacity: 1 - i * 0.22 }}
                  >
                    <span className="text-white/35">{clockOf(r.t).slice(0, 5)}</span>{' '}
                    <span className="text-white/80">{r.who}</span> <span className="text-white/30">·</span> {r.text}
                  </div>
                ))}
              </div>
            )}
          </div>

          <div className="tnum flex flex-none items-baseline gap-[2.4em] font-mono text-[0.68em] text-white/55">
            <span>
              <span className="text-white/85">{fmtInt(Math.round(summary.tokensPerSec ?? 0))}</span> tok/s
            </span>
            <span>
              <span className="text-white/85">${(summary.totalCost ?? 0).toFixed(2)}</span> spent
            </span>
            <span>
              <span className="text-white/85">{fmtTokens(summary.totalTokens ?? 0)}</span> tokens
            </span>
            <span>
              <span className="text-white/85">{c.working}</span>/{agents.length} working
            </span>
          </div>
        </footer>
      </motion.div>

      {/* pointer-revealed controls */}
      <div
        className={`absolute right-5 top-5 z-10 flex gap-2 transition-opacity duration-500 ${
          showUi ? 'opacity-100' : 'pointer-events-none opacity-0'
        }`}
      >
        <button
          onClick={fullscreen}
          aria-label="Toggle fullscreen"
          className="grid h-11 w-11 place-items-center rounded-full border border-glass-line bg-white/[0.08] text-[18px] text-white/70 backdrop-blur-xl transition-colors hover:text-white"
        >
          ⛶
        </button>
        <button
          onClick={onClose}
          aria-label="Exit TV mode"
          className="grid h-11 w-11 place-items-center rounded-full border border-glass-line bg-white/[0.08] text-[18px] text-white/70 backdrop-blur-xl transition-colors hover:text-white"
        >
          ✕
        </button>
      </div>
    </div>
  );
}

// remote/panel/src/components/TvMode.svelte
<script>
  // TV mode — the ambient wall display. Opened via #tv (Settings → TV mode, or
  // just append #tv to the URL on the TV's browser). Design brief: a lot of
  // dark space, a few precise numbers, a quiet list of who's doing what — a
  // room presence, not a workstation. Everything rides the same 1 Hz snapshot;
  // there is no interaction beyond exit/fullscreen (revealed on pointer move).
  //
  // Sizing: the root sets font-size from vw and EVERYTHING inside is em-based,
  // so the composition holds from a 1080p TV to a 4K panel.
  import { onMount } from 'svelte';
  import {
    mc, counts, agentStatus, statusLabel, agentName, fmtTokens, fmtInt, fmtMem,
    dataAge, clockOf,
  } from '../lib/store.svelte.js';
  import { TONE } from '../lib/tone.js';

  let { onclose } = $props();

  const s = $derived(mc.summary || {});
  const c = $derived(counts(mc.agents));
  const sys = $derived(mc.system);
  const age = $derived(dataAge());

  // ---- clock ----
  const time = $derived.by(() => {
    const d = new Date(mc.now || Date.now());
    const p = (n) => String(n).padStart(2, '0');
    return { hm: `${p(d.getHours())}:${p(d.getMinutes())}`, s: p(d.getSeconds()) };
  });
  const dateLine = $derived(
    new Date(mc.now || Date.now()).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' }),
  );

  const link = $derived(
    mc.link === 'linked'
      ? { word: 'linked', cls: 'text-ink3', dot: 'bg-ok' }
      : mc.link === 'relay'
        ? { word: 'mac offline', cls: 'text-warn', dot: 'bg-warn' }
        : { word: 'reconnecting', cls: 'text-crit', dot: 'bg-crit' },
  );

  // Roster: needs-you first, then working, then the rest — capped so a huge
  // fleet still fits on one wall.
  const ORDER = { waiting: 0, exited: 1, working: 2, done: 3 };
  const roster = $derived.by(() => {
    const rows = [...mc.agents].sort((a, b) => (ORDER[agentStatus(a)] ?? 9) - (ORDER[agentStatus(b)] ?? 9));
    return rows.slice(0, 9);
  });
  const overflow = $derived(Math.max(0, mc.agents.length - 9));

  // ---- footer figures ----
  const spendRate = $derived.by(() => {
    const h = mc.history;
    if (h.length < 2) return null;
    const dt = h[h.length - 1].t - h[0].t;
    if (dt < 30_000) return null;
    return Math.max(0, ((h[h.length - 1].cost - h[0].cost) / dt) * 3_600_000);
  });
  const stats = $derived([
    {
      label: 'burn', value: fmtInt(Math.round(s.tokensPerSec ?? 0)), unit: 'tok/s',
      live: (s.tokensPerSec ?? 0) > 0,
    },
    {
      label: 'spend', value: '$' + (s.totalCost ?? 0).toFixed(2), unit: '',
      sub: spendRate === null ? null : `$${spendRate.toFixed(2)}/hr`,
    },
    {
      label: 'tokens', value: fmtTokens(s.totalTokens ?? 0), unit: '',
    },
    {
      label: 'agents', value: String(c.working), unit: `/ ${mc.agents.length}`,
      sub: c.waiting ? `${c.waiting} need${c.waiting === 1 ? 's' : ''} you` : null,
      live: c.working > 0, warn: c.waiting > 0,
    },
  ]);
  const memPct = $derived(sys && sys.memTotalMB ? (100 * sys.memUsedMB) / sys.memTotalMB : 0);

  const recent = $derived([...mc.activity].slice(-4).reverse());

  // ---- chart geometry (em-fluid SVG: viewBox space, stretched to fit) ----
  // The burn horizon along the bottom edge — the room's slow heartbeat.
  const horizon = $derived.by(() => {
    const d = mc.tps.slice(-150);
    if (d.length < 2) return null;
    const W = 1000, H = 120;
    const max = Math.max(...d, 1);
    const p = d.map((v, i) => `${((W * i) / (d.length - 1)).toFixed(1)},${(H - 6 - (H - 18) * (v / max)).toFixed(1)}`);
    return { line: p.join(' '), area: `0,${H} ${p.join(' ')} ${W},${H}` };
  });

  // ---- controls: hidden until the pointer moves; cursor sleeps with them ----
  let showUi = $state(false);
  let hideTimer;
  function poke() {
    showUi = true;
    clearTimeout(hideTimer);
    hideTimer = setTimeout(() => (showUi = false), 3200);
  }
  function fullscreen() {
    if (document.fullscreenElement) document.exitFullscreen?.();
    else document.documentElement.requestFullscreen?.().catch(() => {});
  }

  onMount(() => {
    // Keep the TV awake while the display is up — best effort, Safari may decline.
    let lock = null;
    const acquire = async () => {
      try { lock = await navigator.wakeLock?.request('screen'); } catch {}
    };
    const onVis = () => document.visibilityState === 'visible' && acquire();
    const onKey = (e) => e.key === 'Escape' && onclose?.();
    acquire();
    document.addEventListener('visibilitychange', onVis);
    window.addEventListener('keydown', onKey);
    return () => {
      document.removeEventListener('visibilitychange', onVis);
      window.removeEventListener('keydown', onKey);
      clearTimeout(hideTimer);
      lock?.release?.().catch?.(() => {});
    };
  });
</script>

<div class="fixed inset-0 z-[75] overflow-hidden bg-bg {showUi ? '' : 'tv-nocursor'}" onpointermove={poke} role="presentation">
  <!-- everything scales off this font-size; the slow orbit guards OLEDs -->
  <div class="tv-shift relative flex h-full flex-col" style="font-size:clamp(11px, 1.05vw, 30px)">
    <!-- ---- header ---------------------------------------------------- -->
    <header class="flex flex-none items-start justify-between px-[3.4em] pt-[2.6em]">
      <div>
        <div class="text-[1em] font-semibold tracking-[0.02em] text-ink/85">Mission Control</div>
        <div class="thud mt-[0.75em] flex items-center gap-[0.7em] {link.cls}">
          <span class="relative flex h-[0.42em] w-[0.42em]">
            {#if mc.link !== 'linked'}<span class="absolute inline-flex h-full w-full rounded-full {link.dot} opacity-60" style="animation:mc-ping 1.8s cubic-bezier(0,0,0.2,1) infinite"></span>{/if}
            <span class="relative inline-flex h-[0.42em] w-[0.42em] rounded-full {link.dot}"></span>
          </span>
          {link.word}{#if mc.link === 'linked' && age !== null && age > 5}<span class="text-ink3">· {age}s</span>{/if}
        </div>
      </div>
      <div class="text-right">
        <div class="text-[3.1em] font-medium leading-none tracking-[0.01em] tabular-nums text-ink/90">
          {time.hm}<span class="ml-[0.28em] text-[0.4em] font-normal text-ink3">{time.s}</span>
        </div>
        <div class="thud mt-[0.8em]">{dateLine}</div>
      </div>
    </header>

    <!-- ---- roster ------------------------------------------------------ -->
    <main class="flex min-h-0 flex-1 items-center justify-center px-[4em] py-[1.5em]">
      {#if roster.length}
        <div class="grid w-full max-w-[72em] gap-[0.7em] {roster.length > 3 ? 'grid-cols-2 xl:grid-cols-3' : 'grid-cols-1'}">
          {#each roster as a (a.id)}
            {@const st = agentStatus(a)}
            <div class="flex items-center gap-[0.9em] rounded-[0.7em] border border-line/70 bg-surface/50 px-[1.1em] py-[0.9em] {st === 'waiting' ? '!border-warn/40' : ''}">
              <span class="relative flex h-[0.55em] w-[0.55em] flex-none">
                {#if st === 'working'}<span class="absolute inline-flex h-full w-full rounded-full bg-accent opacity-50" style="animation:mc-ping 1.8s cubic-bezier(0,0,0.2,1) infinite"></span>{/if}
                <span class="relative inline-flex h-[0.55em] w-[0.55em] rounded-full {TONE[st].dot}"></span>
              </span>
              <div class="min-w-0 flex-1">
                <div class="flex items-baseline gap-[0.6em]">
                  <span class="truncate text-[1em] font-semibold text-ink/90">{agentName(a)}</span>
                  <span class="flex-none text-[0.62em] {TONE[st].text}">{statusLabel(st)}</span>
                </div>
                <div class="mt-[0.25em] truncate text-[0.72em] text-ink3">{a.activity || '—'}</div>
              </div>
              <span class="flex-none font-mono text-[0.62em] tabular-nums text-ink3">{fmtTokens(a.tokens ?? 0)}</span>
            </div>
          {/each}
          {#if overflow}
            <div class="flex items-center justify-center rounded-[0.7em] border border-line/40 px-[1.1em] py-[0.9em] text-[0.72em] text-ink3">
              +{overflow} more
            </div>
          {/if}
        </div>
      {:else}
        <div class="text-center">
          <div class="text-[1.3em] font-medium tracking-[0.3em] text-ink2">ALL QUIET</div>
          <div class="thud mt-[1.1em]">no agents running</div>
        </div>
      {/if}
    </main>

    <!-- ---- footer ------------------------------------------------------ -->
    <footer class="relative flex-none px-[3.4em] pb-[2.4em] pt-[1em]">
      {#if horizon}
        <svg viewBox="0 0 1000 120" preserveAspectRatio="none" class="pointer-events-none absolute inset-x-0 bottom-0 h-[6.5em] w-full" aria-hidden="true">
          <defs>
            <linearGradient id="tv-horizon" x1="0" y1="0" x2="0" y2="1">
              <stop offset="0%" stop-color="var(--color-accent)" stop-opacity="0.1" />
              <stop offset="100%" stop-color="var(--color-accent)" stop-opacity="0" />
            </linearGradient>
          </defs>
          <polygon points={horizon.area} fill="url(#tv-horizon)" />
          <polyline points={horizon.line} fill="none" stroke="var(--color-accent)" stroke-width="1.5" vector-effect="non-scaling-stroke" stroke-linejoin="round" opacity="0.35" />
        </svg>
      {/if}

      <div class="relative grid grid-cols-[1fr_auto_1fr] items-end gap-[3em]">
        <!-- recent activity, whispering -->
        <div class="min-w-0 self-end">
          {#if recent.length}
            <div class="thud mb-[0.9em]">recent</div>
            <div class="space-y-[0.55em]">
              {#each recent as r, i (r.t + r.id)}
                <div class="truncate font-mono text-[0.66em] text-ink2" style="opacity:{1 - i * 0.21}">
                  <span class="text-ink3">{clockOf(r.t).slice(0, 5)}</span>
                  <span class="text-ink/75">{r.who}</span>
                  <span class="text-ink3">·</span>
                  {r.text}
                </div>
              {/each}
            </div>
          {/if}
        </div>

        <!-- headline figures -->
        <div class="flex items-start gap-[3.6em]">
          {#each stats as t (t.label)}
            <div class="min-w-[5.5em]">
              <div class="thud flex items-center gap-[0.6em]">
                {t.label}
                {#if t.live}<span class="h-[0.32em] w-[0.32em] rounded-full bg-accent" style="animation:mc-pulse 1.6s steps(2) infinite"></span>{/if}
              </div>
              <div class="mt-[0.5em] flex items-baseline gap-[0.3em] text-[1.75em] font-semibold leading-none tracking-tight tabular-nums {t.warn ? 'text-warn' : 'text-ink/90'}">
                {t.value}{#if t.unit}<span class="thud !tracking-[0.12em]">{t.unit}</span>{/if}
              </div>
              {#if t.sub}<div class="mt-[0.55em] whitespace-nowrap font-mono text-[0.62em] {t.warn ? 'text-warn/85' : 'text-ink3'}">{t.sub}</div>{/if}
            </div>
          {/each}
        </div>

        <!-- machine, in two quiet threads -->
        <div class="flex min-w-0 flex-col items-end gap-[0.9em] self-end">
          {#if sys}
            {#each [{ label: 'cpu', pct: sys.cpu ?? 0, detail: `${sys.cores ?? '—'} cores` }, { label: 'mem', pct: memPct, detail: fmtMem(sys.memUsedMB) }] as b (b.label)}
              {@const pct = Math.max(0, Math.min(100, b.pct))}
              <div class="flex w-[15em] max-w-full items-center gap-[1em]">
                <span class="thud w-[2.4em] flex-none">{b.label}</span>
                <div class="h-[3px] min-w-0 flex-1 overflow-hidden rounded-full bg-line/60">
                  <div class="h-full rounded-full transition-[width] duration-1000" style="width:{pct}%;background:var(--color-ink3);opacity:0.9"></div>
                </div>
                <span class="flex-none font-mono text-[0.62em] tabular-nums text-ink3">{Math.round(pct)}% · {b.detail}</span>
              </div>
            {/each}
          {/if}
        </div>
      </div>
    </footer>
  </div>

  <!-- pointer-revealed controls -->
  <div class="absolute right-5 top-5 z-10 flex gap-2 transition-opacity duration-500 {showUi ? 'opacity-100' : 'pointer-events-none opacity-0'}">
    <button onclick={fullscreen} aria-label="Toggle fullscreen" class="tv-btn">⛶</button>
    <button onclick={onclose} aria-label="Exit TV mode" class="tv-btn">✕</button>
  </div>
</div>

<style>
  .tv-nocursor,
  .tv-nocursor * {
    cursor: none !important;
  }

  /* Burn-in guard: the whole composition orbits a few px over 8 minutes. */
  .tv-shift {
    animation: tv-shift 480s ease-in-out infinite;
  }
  @keyframes tv-shift {
    0%, 100% { transform: translate(0, 0); }
    25% { transform: translate(5px, -4px); }
    50% { transform: translate(-4px, 5px); }
    75% { transform: translate(-5px, -5px); }
  }

  /* Quiet label at TV scale (the app's .hud is fixed 11px). */
  .thud {
    font-size: 0.62em;
    font-weight: 600;
    letter-spacing: 0.22em;
    text-transform: uppercase;
    color: var(--color-ink3);
  }

  .tv-btn {
    display: grid;
    place-items: center;
    width: 44px;
    height: 44px;
    border-radius: 12px;
    border: 1px solid var(--color-line2);
    background: var(--color-raised);
    color: var(--color-ink2);
    font-size: 18px;
    transition: color 0.15s, border-color 0.15s;
  }
  .tv-btn:hover {
    color: var(--color-ink);
    border-color: var(--color-line2);
  }
</style>
